### ISSUE TITLE
Load TreeView child nodes on demand

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [Megabit/Blazorise#1233]
I would like to load child nodes on demand from an API

**Comment by LuisPignataro** [comment]
Hi, using Task.Run (...) I call an async service in GetChilds and it works.
However, it makes the call 2 times and I don't like the use of Task.Run, I was reviewing the code but I don't know what is the best way to Make GetChildNodes work with the async await pattern.

My code is the following:

`GetChildNodes="@(item => GetChildren(item))"`

`protected ICollection<Item> GetChildren(Item item)
        {
            if (item.HasChildren && item.Children?.Count == 0)
            {
                Task.Run(async () =>
                {
                    item.Children = await itemAppService.GetChildListAsync(item.Id);
                    StateHasChanged();
                });
            }
            return item.Children;
        }`

`public class Item{
 public ICollection<Item> Children {get; set;}
 public bool HasChildren {get; set;}
}`

Item objects initially have nothing in the Children property, and the HasChildren property indicates whether the object has Children.

If you have children and the collection is empty, request the list from a service in the backend, populate the collection and return the list.

It is not a good solution, nor is it definitive, it has some problems, due to the misuse of the Task.

I hope some ideas about it!

**Comment by njannink** [comment]
Indeed support for IAsyncEnumerable<T> or Task<IEnumerable<T>> would be preferrable

**Comment by christophwille** [comment]
Because this a rather old issue (but I now too have the issue of loading "on demand" and want to stick with Blazorise TreeView): did anyone every come up with a better way / are there plans for dynamic expanding & loading?

**Comment by David-Moreira** [comment]
@stsrki seems like a good one to revisit soon.
Loading on demand, just like `ReadData` from `DataGrid` is always a nice feature.

**Comment by stsrki** [comment]
Scheduling for 1.2.

**Comment by stsrki** [comment]
I'm working on TreeView improvements ATM, and this ticket came up as the next step.

We already have `GetChildNodes` and `HasChildNodes` APIs for dynamic loading. The problem is that they are not asynchronous. I could change them to `async` but that would be a breaking change for the `1.x` release cycle.

Adding new `GetChildNodesAsync` and `HasChildNodesAsync` feels strange to me as we usually don't add `Async` suffixes to our APIs. And even if I add new APIs, at some point, probably in v2.0 I would replace them with existing APIs. eg, GetChildNodesAsync would become GetChildNodes but with `async Task`.

So, I'm open to suggestions.

**Comment by David-Moreira** [comment]
I would play with the naming and Obsolete marker, documentation helper.
1. Make `GetChildNodes` and `HasChildNodes` obsolete and make the new methods named `GetChildrenNodes` and `HasChildrenNodes`, so basically word play...
2. Introduce the new `Async` versions just like you tought but make them obsolete from the get go, informing that we'll be merging into the regular `GetChildNodes` / `HasChildNodes` on the next major version.

so all in all I think we should just try to document it properly and maintain our usual rules.

**Comment by stsrki** [comment]
@David-Moreira That's what I'm doing now. It seems the best approach without any breaking changes for the time being.

**Comment by stsrki** [comment]
I have added `GetChildNodesAsync` and `HasChildNodesAsync`, which are working now. Regarding the `GetChildNodesAsync` API. I have doubts about two API choices.

- `Func<TNode, Task<IEnumerable<TNode>>> GetChildNodesAsync`
- `Func<TNode, IAsyncEnumerable<TNode>> GetChildNodesAsync`

Making it `Task`-able seems to be easier to implement and to consume, but I would really like to have feedback from users before merging.
