### ISSUE TITLE
LayoutHeader moving

### ISSUE THREAD

**Issue by gallwood** [Megabit/Blazorise#1283]
**Describe the bug**
I have a MainLayout file that contains a Layout component with a LayoutHeader and LayoutContent. Inside the header is a Bar comp.

In my page body, if I have a simple table with more that 35 rows in it, once I scroll down to the bottom of the page, the Bar in the header scrolls out of view.

**Expected behavior**
I would expect the Header bar to remain static.

Example repo:
https://github.com/gallwood/Scrolling

**Comment by MitchellNZ** [comment]
Thanks for taking the time to make an example repo!

I haven't had chance to test this myself yet with your example... 
But I have a feeling this might be fixed with changes in #1090 🤔

I will give it a try tomorrow, but if you get round to it before me, I'd recommend trying out the [latest preview version](https://github.com/stsrki/Blazorise#try-preview) of Blazoirse with this to see if its already fixed in 0.9.2.

**Comment by stsrki** [comment]
@gallwood On which branch you tried? The changes that @MitchellNZ was talking about are still in PR, and needs to be merged.

**Comment by gallwood** [comment]
@stsrki good point. I simply used the 0.9.2 release from your private package store as referenced above. If I get time tomorrow or Friday, I can try the branch the PR is coming from. (In theory :) )

**Comment by stsrki** [comment]
No worries, I will release it soon as preview anyways. There just needs to be some smaller things done by @MitchellNZ

**Comment by MitchellNZ** [comment]
@stsrki @gallwood 
I just tested this, and I don't think any of the changes I have done will fix this, unfortunately.

Looks like it could be a new bug related to not having a sidebar.
I will need to investigate further, as this is not typically a scenario I test with.

Thanks for reporting!
