### ISSUE TITLE
Chart: RemoveDataSet API

### ISSUE THREAD

**Issue by mortezabarzkar** [Megabit/Blazorise#1842]
Hi
I can add dataset via Chart.AddDatasetsAndUpdate() and it's work normally
but when i want to remove dataset via Chart.Data.Datasets.RemoveAt(Chart.Data.Datasets.FindLastIndex(c => c.Label == item));
it was removed from collection but still are showing in ui !!!

**Comment by stsrki** [comment]
When you change `Chart.Data.Datasets` directly there is no way to tell chartsjs that something has changed. remember, Blazor and JS objects are separated.

You should be calling `chart.Update()` after you remove the dataset, but here we also have a problem since internally a `dirty` flag will not be set(because you modified data directly) and no update would be passed down to JS.

The only way for you is to `chart.Clear()` datasets and then re-add them. That would work.

In the meantime, I can consider adding a method `RemoveDataset(int index)`.

**Comment by mortezabarzkar** [comment]
if i use chart.Clear() all datasets will be remove and it will be violate the live view.
if you can add RemoveDataset(int index) it's will be useful
