### ISSUE TITLE
SelectEdit when TValue="string" and selecting null, then Value not returned in the event args

### ISSUE THREAD

**Issue by brettwinters** [Megabit/Blazorise#185]
Hello 

I think I found an issue as follows: 

In the case of Int?, selecting "None" prints "" (empty/null) in the Console. Selecting the others prints "1" and "2" as expected.
```html
<SelectEdit TValue="int?" SelectedValueChanged="@((v) => Console.WriteLine(v))">
    <SelectItem Value="@((int?)null)">None</SelectItem>
    <SelectItem Value="@((int?)1)">One</SelectItem>
    <SelectItem Value="@((int?)2)">Two</SelectItem>
</SelectEdit>
```

But in the case of String, selecting "None" prints "None" in the Console (ie the text property and not the "Value" property). I think this should print empty/null
```html
<SelectEdit TValue="string" SelectedValueChanged="@((v) => Console.WriteLine(v))">
    <SelectItem Value="@((string)null)">None</SelectItem>
    <SelectItem Value="@((string)"one")">One</SelectItem>
    <SelectItem Value="@((string)"two")">Two</SelectItem>
</SelectEdit>
```

Selecting the others prints "one" and "two" as expected (ie the "value" property)

**Comment by stsrki** [comment]
It seems this is a bug in either Blazor or the html itself. I will need to investigate more. When the null or empty strings are used for `<option>` tag then the select `onchange` will use an option **Text** instead of it's **Value**. Hopefully I will find a workaround, but if not I will report it to the Blazor team and see how it goes.

**Comment by stsrki** [comment]
Possibly the same problem: https://github.com/aspnet/AspNetCore/issues/13440

**Comment by stsrki** [comment]
I'm afraid this is by design. 

1. https://stackoverflow.com/a/34266512
2. https://html.spec.whatwg.org/multipage/form-elements.html#the-option-element

There is not much for me to do here. I will leave it open in hope that Blazor team does something so that I can get the actual value from `option`.
