### ISSUE TITLE
DataGrid: Race condition with OnPageSizeChanged and OnPageChanged events

### ISSUE THREAD

**Issue by nguyenhthai** [Megabit/Blazorise#1938]
**Describe the bug**
Hi. Not sure if this is an actual bug but while working with DataGrid component under v0.9.3-rc2, I encountered one particular issue with those events. Let's say we have 100 data records and handle the data loading manually by using **OnReadData** with the default page size (5 per page). The grid would display the first five records with paging ranging from page 1 to page 20. Let's say we move to page 5 and then change the page size to be 100 instead. Now, at this point, the **OnPageSizeChanged** event will be triggered and the **OnReadData** is once again triggered. However, during this time, the page is not at page 5 anymore and the component calculated the page is different than previously, which would trigger the **OnPageChanged** event, which in turn trigger the read data logic again. At this point, the **OnReadData** that is triggered from **OnPageSizeChanged** is still await from one of my service  which returns the result set from the database. Then comes the **OnReadData** from **OnPageChanged** which also tries to execute the service the second time and thus resulted in duplicate DB calls while the first one has not finished yet.

Here is my OnReadData
```
async Task OnReadData(DataGridReadDataEventArgs<TestModel> e)
{
    if (!e.CancellationToken.IsCancellationRequested)
    {
        callingTime++;
        try
        {
            var list = await TestService.GetList("Something");
            var response = list.Skip((e.Page - 1) * e.PageSize).Take(e.PageSize).ToList();

            result = new List<TestModel>(response);
            total = test.Count;

            await InvokeAsync(StateHasChanged);
        }
        catch (Exception exception)
        {
            throw;
        }
    }
}
```
If this is the intended behavior, how should I avoid the read data being triggered multiple times?

**Comment by David-Moreira** [comment]
I actually noticed this a few weeks ago, and issue this PR #1886. So we introduced this CancellationToken that issues a CancellationToken if you trigger various page changed events. Internally it checks if it has been cancelled or not before issuing another ReadData. 

Additionally, we also pass that Token to you, so you yourself can check it. And I see you're already checking it. But once it gets to calling the BD we can't really do anything about it, it's already there. But if you issue various page size / page changed events, you should see the calls being quite mitigated as the cancellations are being issued.

However, your results are always coherent right? You always have the results corresponding to the latest triggered event, right? 

But like you've said sometimes it's just a race condition, I believe there isn't much more you can do about that.

**Comment by nguyenhthai** [comment]
I went back to the provided example and noticed one thing different: `await Task.Delay(random.Next(800));`

After adding that to my OnReadData, the cancellation works properly in the pipeline. So the delay definitely helps fixing the race condition. Just wonder if I could use any arbitrarily number for the delay (make it minimal as possible) and also should the document mentions about the delay for retrieving data from another endpoint?

**Comment by David-Moreira** [comment]
Hello @nguyenhthai 
Since Datagrid does almost no work internally, as you click the buttons, it will just pump out those events as soon as they come.
Blazorise.Datagrid would need to have a mechanism itself to verify if events are being triggered within a certain threshold time, if we wanted to really avoid calling OnReadData, however that would certainly have some performance cost.

With the current implementation, having a slightly delay just to make sure the user does not quickly trigger an event is a way to avoid additional processing, however it does affect your app response time.
So `await Task.Delay(random.Next(800));`  is a way we can simulate some ongoing work.

For example, you could make use of the Cancellation Token on your work pipeline, if you had several long work, you can check several times if the Cancellation Token was cancelled before continuing and updating the data.
Like this:
```
    async Task OnReadData( DataGridReadDataEventArgs<Employee> e )
    {
        if ( !e.CancellationToken.IsCancellationRequested )
        {
                //Long Work 1.
                // Simulate a long work // This one might not be easilly cancellable as Datagrid just receives every page click and instantly calls OnReadData
                await Task.Delay( random.Next( 800 ) );

                //Long Work 2.
                //However if you have more work or if you can segregate your work and make checks: 
                //Now this work will be cancelled if meanwhile the user triggered another page event and work 1. didn't finish
                if ( !e.CancellationToken.IsCancellationRequested )
                {
                    await Task.Delay( random.Next( 1000 ) ); // Another big work here
                }
            await InvokeAsync( StateHasChanged );
        }
    }
```

If for some reason you are having trouble with the latest data syncing up with the latest triggered event, you could set a timestamp tracking the last time OnReadData was called and if by the end of the work, it does not match the local method timestamp, then it means there's a more recent OnReadData and the current processing should be ignored.

**Comment by stsrki** [comment]
@David-Moreira Can we close this ticket?

**Comment by David-Moreira** [comment]
I don't see why not. If there was an issue here, we would have more complaints already. 😆
