### ISSUE TITLE
 NumericEdit bugs or compatibility issues

### ISSUE THREAD

**Issue by wartim** [Megabit/Blazorise#2292]
1 I am using Google Chrome,the following debugging is in Google Chrome
2 When I use the NumericEdit component, it is only displayed as a normal text input box, without input verification, and no up and down arrows.
3 And the result of the source code DEMO running is the same
4 Then I went to check the source code and found that it used 

```
  <input inputmode="numeric" class="form-control"/> 
```

And whether there is a compatibility problem with inputmode?
5 Finally, I went to check the online documentation of the official website and found that the example page called 
  https://blazorise.com/examples/forms/numeric-basic/
using F12, the generated html was

```
   <input type="number" value ="123" class="form-control">
```

6 The html generated in the document is different, so the examples in the document are displayed normally, but the use in the project is abnormal

**Comment by stsrki** [comment]
The `<input type="number" value ="123" class="form-control">` that you see in the documentation is actually wrong. To understand why I must explain. When Blazorise was first created over two years ago(almost three now) there was no good way to do a public-facing webpage that would have support for SEO, markdown, and many other things. So I had to settle for Jekyll based app to create a documentation page. So for the code examples, a used the real code output from Blazorise, but that can lead to some things not being updated regularly. As you see it today.

Now, the new fully Blazorise documentation is in the works but I still have a lot of work to do. Hope to end it soon.

As of NumericEdit, the right HTML is `<input inputmode="numeric" class="form-control"/> `. The reason is that I need to have regular `input="text"` instead of `input="number"` because I must have a way to get and set text selection with JavaScript code-behind. And with number input that is not possible.

In 0.9.4 version you will also have spin buttons

![image](https://user-images.githubusercontent.com/900302/117004735-b12e7700-ace6-11eb-9b1d-648951ad4ff8.png)

**Comment by wartim** [comment]
@stsrki 
Thanks for the reply, I don’t know if I understand it right or not, 

I am using the master version (0.9.3.6), I see there is a preview version: 0.9.4-preview3.3, you mean it is in 0.9.4 Will it be repaired? That’s great. I don’t know when the official stable version will be released. 

In addition, if I directly modify the source code in 0.9.3.6, it is not advisable to force inputmode="numeric" to type="number"?

Can I only temporarily stop using this component in 3.6, or try 0.9.4-preview3.3? How other people solve this problem

**Comment by stsrki** [comment]
In 0.9.4.x the missing spin buttons will be solved. Regarding the `type="number"` that is not going to be implemented. As stated before, I'm using regular input for the numbers for the reason that I'm doing all the formatting of numbers by myself. If I would have `type="number"` then it would all be done by the browser. And the problem with browsers is that it is not possible to `localize` number input. Also, it is not possible to change the decimal separator. All those things are currently done with NumericEdit.

**Comment by wartim** [comment]
thanks
