### ISSUE TITLE
24 time format of TimePicker

### ISSUE THREAD

**Issue by kusayjaara** [Megabit/Blazorise#2351]
**Describe the bug**
When using TimeEdit, the time is shown always in the 12 hours time format, even if the local format is 24 hours format.
In the image, you see two time pickers, one done with html and the other done by TimeEdit.

**Expected behavior**
TimePicker must show time in 24 hours if the format of user computer is 24 hours .

```
<td><input type="time" @bind-value="timeValue" /></td>
<td><Blazorise.TimeEdit @bind-Time="timeValue"></Blazorise.TimeEdit></td>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/76060531/117966035-bfeade80-b323-11eb-9170-6988b1553dad.png)

**Comment by BrettButcher** [comment]
Yes, I agree. I am seeing this issue too. But also when trying to use the Format rather than just locale.

`<Blazorise.TimeEdit TValue="DateTime" @bind-Time="@editGame.WhenToRun"  Pattern="@TimeFormat" />
 `    
             ... shows 14:00 as 2.00 

`<input type="time" @bind="@editGame.WhenToRun" @bind:format=@TimeFormat />`
             ... shows 14:00 as 14:00

In the code:
`        private const string TimeFormat = "HH':'mm':'ss";`

The single quotes around the colons came from a combination of sources, starting here:
[https://stackoverflow.com/questions/66277278/blazor-wasm-net-5-input-time-do-not-show-correctly](url)

I was wondering if 'Pattern' is the correct way to set this up, however, '@bind:format' barfs so..?
Many thanks

**Comment by stsrki** [comment]
@BrettButcher I can confirm the issue on my side. The problem is in how I convert to time string internally. It is a small fix. But the bigger problem is still present. There is no real way to force the use of the 24-hour format. It is completely in control by the browser and/or system.

I will fix the invalid format and release it as part of the next 0.9.3 patch.

**Comment by BrettButcher** [comment]
> @BrettButcher I can confirm the issue on my side. The problem is in how I convert to time string internally. It is a small fix. But the bigger problem is still present. There is no real way to force the use of the 24-hour format. It is completely in control by the browser and/or system.
> 
> I will fix the invalid format and release it as part of the next 0.9.3 patch.

Thank you @stsrki  ... Yes, the locale issue is a wider one with browser dependencies etc. Also the 'Timespan' issue? I don't need/use it actually, preferring that it pulls directly from the datetime, but it is there is the docs so might crop up again. Maybe just remove it and use datetime, as I imagine most folks will be using that anyway... unless its a trivial fix. Great work and thanks again 👍

**Comment by stsrki** [comment]
TimeSpan is still needed. I implemented it because it was requested many times.
