### ISSUE TITLE
DateEdit Format property

### ISSUE THREAD

**Issue by leonardotvd** [Megabit/Blazorise#2381]
I would like to know if it is possible to implement in DateEdit a property called Format to change the date format? In my project, all dates are displayed and picked using format dd/MMM/yyyy, for example, 15-may-2021. That property exists in other components such as Telerik DatePicker. I don't want to mix inputs in my forms and I've been mostly using Blazorise to follow the project pattern.

**Comment by stsrki** [comment]
Unfortunately, it is not possible with the current DateEdit. Since it is basically an `input type="date"` it is limited by the browser. I have a plan to add fully custom date picker, see https://github.com/Megabit/Blazorise/issues/2062

I have already done a similar thing in Material provider so I think it is the best way.

**Comment by stsrki** [comment]
Going to be part of new DatePicker component #2403
