### ISSUE TITLE
BarEnd in horizontal mode is not aligning content to the right with bootstrap 5

### ISSUE THREAD

**Issue by WolfgangKluge** [Megabit/Blazorise#2451]
When switching to bootstrap 5, items inside `BarEnd` are not aligned to the right anymore.
In vertical mode it seems to still work as expected (the items are still aligned to the bottom)

**To Reproduce**
1. Use your own demo and switch bootstrap version from 4.6.0 to 5.0.1
2. See navbar at the top (the menu items "language", "theme" and "github" are there just as if you put them into another `BarStart`)

**Comment by stsrki** [comment]
Bootstrap 4 is still not supported. We plan to start working on it soon, #1103

---

I would say the reason, why it doesn't work, is because in BS5 `left` and `right` keywords are changed. They are now named `start` and `end`. And so, instead of having `ml-auto` for `BarEnd` margin class-names, we need to have `me-auto`.

**Comment by stsrki** [comment]
PS. Closing now since it is not an issue in current provider and we will track progress in another ticket.

**Comment by WolfgangKluge** [comment]
Sorry, I've overseen #1103.
Thanks
