### ISSUE TITLE
Allow Null Value in SelectList

### ISSUE THREAD

**Issue by bodeg** [Megabit/Blazorise#2526]
Is it possible to allow the user to select Null Value in SelectList?
same for Select

With regards, alon.

**Comment by David-Moreira** [comment]
Hello @bodeg(alon),
depends on how you want to use it, as long as you use it, similar to this, it this should work just fine:

```
<Blazorise.Select TValue="string" SelectedValue="@selectedItem" SelectedValueChanged="SelectedValueChanged">
@foreach (var item in stuff)
{
    <Blazorise.SelectItem TValue="string" Value="item">@item</Blazorise.SelectItem>
}
</Blazorise.Select>

@code{

    private string selectedItem;
    private List<string> stuff = new()
    {
        null,
        "123",
        "456"
    };

    private void SelectedValueChanged(string e)
    {
        selectedItem = e;
    }
}
```

**[Image: SelectedValueChanged - Null Handling]**
![image](https://user-images.githubusercontent.com/22283161/123539084-e2985180-d72f-11eb-965a-887b116fac85.png)

**Comment by stsrki** [comment]
You can safely use null values, as long you **don't assign** display name for the null option. It is a limitation in Blazor and how the browsers work in general. We already had similar requests but we don't want to stray too much from default `<select>` element behavior, even if it's _wrong_.

---

What I did in my own projects to handle `null`, instead of null I assign it some **dummy** value, like `<empty>`, or `-1`, the choice is yours. Then when I read from or write to the backend I have a simple conversion method to and from `null` value.

**Comment by bodeg** [comment]
Thanks for your reply - I fine with the suggested implementation.

When I opened the issue, I was thinking of something more "friendly", like the small 'x' in the Autocomplete

![2021-06-30_10-19-37](https://user-images.githubusercontent.com/1940943/123918727-d3620f80-d98c-11eb-8851-a531bb8a4d70.png)

**Comment by stsrki** [comment]
Autocomplete is a different control because it has a search field that you can clear, that's why a clear icon makes sense. Select on the other hand can have multiple meanings for the "null" value. It can be `null`, `0`, `empty`, whatever the user can define for their projects.

Also, you can make something similar by using addons

```cshtml
<Addons>
    <Addon AddonType="AddonType.Body">
        <Select TValue="string" @bind-SelectedValue="@selectedValue">
            <SelectItem TValue="string" Value="@(null)"></SelectItem>
            <SelectItem TValue="string" Value="@("1")">1</SelectItem>
            <SelectItem TValue="string" Value="@("2")">2</SelectItem>
            <SelectItem TValue="string" Value="@("3")">3</SelectItem>
        </Select>
    </Addon>
    <Addon AddonType="AddonType.End">
        <Button Color="Color.Secondary" Outline Clicked="@(()=>selectedValue = null)">
            <Icon Name="IconName.Times" />
        </Button>
    </Addon>
</Addons>
@code{
    string selectedValue = "1";
}
```
