### ISSUE TITLE
Fast clicking makes the checkbox lagged

### ISSUE THREAD

**Issue by cotur** [Megabit/Blazorise#2574]
When I click few times to a checkbox, it's become lagged. What is the reason of it? How we can make it smooth.

![](https://user-images.githubusercontent.com/16813853/118758752-39457c80-b8a2-11eb-8877-525b43624e3a.gif)

**Comment by stsrki** [comment]
Whenever a component has a  **two-way** binding, Blazor will trigger `StateHasChanged` and it will refresh the entire page or most of the page. Usually, it is not a problem because internally it will try to keep track of components states and will diff and only update what is really changed. I suspect in this case you have too many single smaller components on a page and Blazor diffing needs a longer time to check every one of them. One solution would be to split them into groups of components. For example, all inputs on one tab go into `Tab1Fields`, tab 2 go into `Tab2Fields`, etc. That way less diffing will be needed.

**Comment by David-Moreira** [comment]
That's however still a strange delay. Doesn't hurt to take a look. @cotur Could you provide a repository showcasing your problem, please?

**Comment by cotur** [comment]
I will prepare [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example). Will notify you when it's ready.
