### ISSUE TITLE
DataGrid: responsive layout

### ISSUE THREAD

**Issue by andz-gl** [Megabit/Blazorise#2634]
Optionally render DataGrid via DIVs (not via table tr td). Like
div class="row"
    div class="col-2" cell 1 /div
    div class="col-2" cell 2 /div
    ....
/div

it will make DataGrid really responsive for mobile devices

**Comment by stsrki** [comment]
Hi @andz-gl 

At the moment we don't have plans to use divs instead of tables for DataGrid. Mainly because DataGrid is meant to display tabular data and semantically a `table` is the best way to do it. Also, we use table implementation based on different providers(Bootstrap, Bulma, AntDesign). If we would go with divs we would have to implement every column, row, and cell from scratch and then do it for every possible CSS provider that we support. Not to mention effects like hover, striped, borderless, responsive, and some more.

**Comment by andz-gl** [comment]
got it, thank you for quick response! please think about mobile devices (so that users could see information without horizontal scrolling)
