### ISSUE TITLE
DataGrid multiselect - maintain selected rows after refresh

### ISSUE THREAD

**Issue by robalexclark** [Megabit/Blazorise#2690]
I have a datagrid as follows:

```
    <DataGrid ElementId="BulkMiscParametersGrid-DataGrid-0" TItem="BulkMiscParameterSelectionViewModel" Data="@bulkMiscParameterSelectionViewModel"  SelectionMode="DataGridSelectionMode.Multiple" @bind-SelectedRows="@selectedAnimals">

        <DataGridMultiSelectColumn TItem="BulkMiscParameterSelectionViewModel" Width="30px"></DataGridMultiSelectColumn>

lots of columns...
        </DataGridColumn>
    </DataGrid>
```
After I have worked on the @selectedAnimals, saved and refreshed from the db I would like the currently selected animals to be maintained on-screen. I note that the list of @selectedAnimals still does have the animals, but the datagrid does not actually show that these rows are selected and the DataGridMultiSelectColumn does not have the checks against these animals.

**Comment by David-Moreira** [comment]
If you refreshed the data from the bd... Then certainly you have fresh data and new in memory reference for your items and the selectedrows information is stale, because internally Datagrid compares items by reference, even if the information is basically all the same. 

This should happen for both selectedrow and selectedrows if I'm not mistaken. 
Which means that you should take a look at the previous selected rows... Refresh from bd, and then populate selected rows with the new data.
Tell us if this helps.

**Comment by robalexclark** [comment]
Got it - I saved the IDs on the rows into a list, did a refresh and then repopulated selectedAnimals from those rows wiith those IDs

**Comment by David-Moreira** [comment]
Exactly. Great! 👍
