### ISSUE TITLE
Tabs with selectors on the bottom but stuck to the bottom of a window

### ISSUE THREAD

**Issue by Luk164** [Megabit/Blazorise#2708]
**Is your feature request related to a problem? Please describe.**
A new tab position, bottomWindow, which makes the selectors position relative to window and pins it to bottom (see screenshot).

![image](https://user-images.githubusercontent.com/30559213/126678585-22e185a6-a736-4965-99a6-125e7d1bec49.png)

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

### Additional context
BTW, I do not see any way to add css styles/classes to Tabs items. The only element accepting them is Tabs itself.

**Comment by stsrki** [comment]
I don't think this needs to be implemented in the library because it's not that common, and also with just a little CSS you can already do it yourself. Here I just modify a couple of lines to move tabs at the bottom. I'm sure you can do it better.

First, adding a custom class to a simple:

![image](https://user-images.githubusercontent.com/900302/126706588-c4549736-152c-46d6-bd85-55033e06def5.png)

and here are tabs at the bottom of the screen.

![image](https://user-images.githubusercontent.com/900302/126706472-2ab6d526-4ef6-421b-8a34-638f643e82af.png)

**Comment by Luk164** [comment]
Wait, I get the my-custom-class, but where did the style on the ul element come from?

**Comment by stsrki** [comment]
I have added them manually

```cshtml
<Tabs SelectedTab="@selectedTabName1" SelectedTabChanged="@OnSelectedTabChanged1" Style="position: fixed; bottom: 0">
    ...
</Tabs>
```

**Comment by Luk164** [comment]
> I have added them manually
> 
> ```cshtml
> <Tabs SelectedTab="@selectedTabName1" SelectedTabChanged="@OnSelectedTabChanged1" Style="position: fixed; bottom: 0">
>     ...
> </Tabs>
> ```

Oh, so the ones defined in Tabs is applied to the menu? A thought it was for the whole thing. Now I get it.

**Comment by stsrki** [comment]
Yes, Tabs represent the navigations. But they can be used to contain the Content part. I did this a while ago to make it simpler.
