### ISSUE TITLE
Datagrid-multi-selection: Re-populating the underlying list and maintaining the selection results in a wrong selection

### ISSUE THREAD

**Issue by StefanOssendorf** [Megabit/Blazorise#2734]
**Describe the bug**
When datagrid is for multi-selection configured and the Data list is cleared and re-populated including the SelectedRows property to keep the old selection. An old "orphan" selection which is kept in the SelectedRow property is being added to the SelectedRows property which results in a SelectedRows.Count + 1 selection. Where 1 is an old item which necessarily does not exist any more.

**To Reproduce**
Minimum working example with step by step instructions: https://github.com/StefanOssendorf/mwe-blazorise-datagrid-multiselect-refresh-issue
Everything for the demo can be found in this file: https://github.com/StefanOssendorf/mwe-blazorise-datagrid-multiselect-refresh-issue/blob/main/DatagridSelectionIssueWhenRepopulating/Pages/Index.razor

**Expected behavior**
Only the `SelectedRows` property is responsible for the selection and _not_ the `SelectedRow` in addition.

**Additional context**
I would propose to make a use of both properties (`SelectedRow` and `SelectedRows`) at the same time invalid resulting in an `InvalidOperationException` to state either use `SelectedRow` (with `DataGridSelectionMode.Single`) or `SelectedRows` (with DataGridSelectionMode.Multiple`).

Side-note: When you change the MWE from above from `DataGridSelectionMode.Multiple` to `DataGridSelectionMode.Single` you get a `NullReferenceException` but I couldn't figure out why.

**Comment by David-Moreira** [comment]
Hello @StefanOssendorf 
We really appreciate that you took your time for such a detailed working example, it really help us with analysing the problem and getting back to you faster.

> Side-note: When you change the MWE from above from DataGridSelectionMode.Multiple to DataGridSelectionMode.Single you get a NullReferenceException but I couldn't figure out why.

Internally we set SelectedRows to null if Datagrid is set to `DataGridSelectionMode.Single`. The null comes from your razor code trying to access a null collection:
![image](https://user-images.githubusercontent.com/22283161/127057330-b2113627-3625-47eb-b929-0cbb11617cbf.png)

As for the reported problem, you're right. `SelectedRows` is taking in a "stale" `SelectedRow` incorrectly. 
Caused by #2565
This PR introduced a SelectionModeChanged Handler... so if our users, want to switch between modes, the grid correctly synchronizes the data.
1- If it goes from Single to Multiple Selection, it sets the `SelectedRows `to take in the currently `SelectedRow`.
2- If it goes from Multiple to Single Selection it clears the `SelectedRows`, setting them back to the original default value of null, but leaving `SelectedRow `as it was already set.
![image](https://user-images.githubusercontent.com/22283161/127057813-ece3deed-c518-45c6-a83d-b7b7d23b34d0.png)

We appreciate the feedback and suggestion about throwing an `InvalidOperationException` but we've decided to maintain both `SelectedRow` /  `SelectedRows` working simultaneously. It's up to the developer, how he'd like to use these. However the problem you've reported is indeed a bug and we'll be fixing it.
With this said, a temporary workaround for your problem is to just set `SelectedRow `to null
`SelectedRow="null"`

In the meantime we'll fix the problem, not taking in a possible stale `SelectedRow` into the `SelectedRows` collection.

**Comment by StefanOssendorf** [comment]
Hello @David-Moreira ,

thank you for your detailed answer as well :-).

Okay, for the `NullReferenceException` I can only facepalm that I missed the usage in the markup. I fixed it in the method though for my test 😂 .

Didn't think about switching dynamically from Multiple to Single or vice versa. Could be a use case, that should not throw.

Thanks for the work around, quick fix and maybe even a slight perfomance improvement 😄 .

**Comment by stsrki** [comment]
@David-Moreira should we fix this for 0.9.4 or 0.9.5?

**Comment by stsrki** [comment]
Nvm, it's too early and I've just seen your PR 😆
