### ISSUE TITLE
Select with bind is not updating when value is null

### ISSUE THREAD

**Issue by austibor** [Megabit/Blazorise#2806]
Hi,

I got the following code:

```c#
<Select TValue="int?"  @bind-SelectedValue="@SpecDocumentId">
    <ChildContent>
        <SelectItem TValue="int?"  Value="@((int?)null)">Null</SelectItem>
         @foreach (var document in SpecDocuments)
        {
            <SelectItem TValue="int?"  Value="@document.Id">@($"{document.Name} ({document.Description})")</SelectItem>
        }
    </ChildContent>
</Select>

@code{

public int? SpecDocumentId
    {
        get {return Item.SpecificationDocumentId;}
        set {Item.SpecificationDocumentId = value;}
    }
}
```

The problem:

I can select the documents and they will get assigned to the SpecDocumentId just fine.
When I select the 'Null' option the binding setter on the SpecDocumentId won't get called and value doesn't get updated.
The drop down in UI will show 'Null' selected but the SpecDocumentId will return previous integer value instead of null.

**Comment by stsrki** [comment]
This is a known issue. The problem is in how browsers work in general. When you have an empty value for the `<option>` element it will take its **text** or content and use that for the selected value. Which is obviously wrong.

Instead of `Null` text leave it empty and see if that helps, eg `<SelectItem TValue="int?"  Value="@((int?)null)"></SelectItem>`

**Comment by austibor** [comment]
Thank you, that did the trick.
