### ISSUE TITLE
InvalidCastException: Unable to cast object of type 'System.String' to type 'Blazorise.IFluentSizing'.

### ISSUE THREAD

**Issue by robertkhou** [Megabit/Blazorise#2820]
After blazorise update it caused an error 
`InvalidOperationException: Unable to set property 'height' on object of type 'Blazorise.CardImage'. The error was: Unable to cast object of type 'System.String' to type 'Blazorise.IFluentSizing'.
`

`<CardImage Source="/img/logo.png" height="38px"></CardImage>`
`  <CardImage Source="/img/user-profile.png" Class="userprofile-round-img" height="26" width="26" Alt="Me"></CardImage>
`
` <CardImage Source="/img/flags/us.png" height="100%"></CardImage>`
We set the height and width using height/width, but it seems like these attributes are no longer supported, how do you set the height and width now?

**Comment by stsrki** [comment]
It is a known issue. I have reported the issue on the donet repository but unfortunately, it will not be fixed. The problem is that VS or razor engine doesn't recognize `height` vs `Height`. The `Height` is Blazorise new utility for setting the standard element sizes.

The workaround is to use the `Style` parameter with `height` and `width`. 

**Example:**

```cshtml
<CardImage Source="/img/user-profile.png" Class="userprofile-round-img" Style="width: 26px; height: 26px;" Alt="Me"></CardImage>
```

and it is more the _right_ way. As far as I know, height and width on an element are not recommended any more: https://stackoverflow.com/questions/39372619/is-it-still-relevant-to-specify-width-and-heigth-attribute-on-images-in-html

**Comment by robertkhou** [comment]
thanks!

Also the parameter "IsRightAligned" does blazorise still use this?
<BarDropdownMenu Style="min-width:220px;" IsRightAligned="true">....</BarDropdownMenu>

**Comment by stsrki** [comment]
Do you mean on the Dropdown component? It is named `RightAligned` now.

**Comment by robertkhou** [comment]
> Do you mean on the Dropdown component? It is named `RightAligned` now.

https://blazorise.com/docs/components/dropdown/#attributes

Before: <DropdownMenu IsRightAligned="true"></DropdownMenu>
After: <DropdownMenu RightAligned="true"></DropdownMenu>
