### ISSUE TITLE
Select dropdown seems to need a explicit select of item to bind to element (shown value not bound)

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#2826]
Hi again, just an observation/suggestion/thought here

1. A page has a **Select**
2. Starting up the page, the Select shows the first SelectItem as "selected" in the dropdown
3. But that first value is never bound to the bind property when page is posted, even though its the "selected" value.
4. And because its not really selected, the `OnSelectedValueChanged` never fires.

Wouldn´t it make sense that **the bound value is the shown value** in the select? **Or** add some "BindToShownValue"/"BindToFirst" attribute?

```csharp
int selectedTimeLength; //alsways default(int) == 0 and not "selected 30
```

```razor
<Select TValue="int" @bind-SelectedValue="@selectedTimeLength" >
    <SelectItem Value="30">30 min</SelectItem>//value shown but never bound because never really selected
    <SelectItem Value="60">60 min</SelectItem>
    <SelectItem Value="90">90 min</SelectItem>
</Select>
```

I know that I can (and I will) do some version of the following

```csharp
int defaultMinimumTimeLenght = 30;
```

```xml
<Select TValue="int" @bind-SelectedValue="@MyModel.TimeLength" >
    <SelectItem Value=@defaultMinimumTimeLenght >@defaultMinimumTimeLenght min</SelectItem>
    <SelectItem Value="60">60 min</SelectItem>
    <SelectItem Value="90">90 min</SelectItem>
</Select>
```
but then I need to do something ugly like this when I post

```csharp
 // if nothing was selected use the default
  if(MyModel.TimeLength== 0)
  {
      MyModel.TimeLength = defaultMinimumTimeLenght;
  }
else
{
 MyModel.TimeLength = selectedTimeLength;
}
```

I have been busy with other stuff than UI for over 1.5 months so little rusty at the moment so I totally might be missing something trivial, sorry for that if that is so!

p.s
I could probably also add the following and do some validation but I want to have a default value pre-selected as a minimum value.

```xml
<SelectItem Value="0">"Select length"</SelectItem>
```

**Comment by David-Moreira** [comment]
Hello @sturlath,
Why can't you initialize int `selectedTimeLength;` or even your ViewModel to 30, since that's the correct default value for your use case, not 0?

**Comment by sturlath** [comment]
Yes I was thinking this over and I  think I'll be adding it to my ViewModel and validating it in my service. Its just that in this case I had started with the UI and was coming to an old code.

But what if somebody needs to load dynamic data to a list? Would binding the shown/first item there not be of value?

**Comment by David-Moreira** [comment]
Hmm okay, let's talk about this, In my opinion, I think it might be wrong to assume this behaviour. 

If you provide a value to the `Select`, outside of the `SelectItem`'s existing values
 - It can't find a match, so I don't think it should mutate it. 
 - Even though visually displays the first item (`<option>`), because that's the standard browser behaviour for `<select>` when no value is selected, none of the `<option>` are actually considered as `selected` behind the covers.
 - There was no user "command" to actually change the value provided initially by the programmer.

Dynamic data should fall into the same line of thinking as static data, just provide the value you'd like to be the default starting `<option>`, be it the first or any of them.

Now if you really wanted to make it work like that for your use cases, you should be able to override the Blazorise's `Select` behaviour implementing your own use cases, like this one for example.

@stsrki want to give a 3rd opinion on this matter?

**Comment by stsrki** [comment]
I would line with @David-Moreira. The Select component should only be able to work with data that you explicitly provide it. If you want to have a `default` value then it should be part of the SelectItem value.

**Comment by sturlath** [comment]
Yes I agree :-) Thanks and sorry for wasting your time with stuff like this ;-)

**Comment by stsrki** [comment]
No worries. We like the new ideas. Sometimes they don't match but most of the time they improve Blazorise 😉
