### ISSUE TITLE
Relation between Blazorise and Material

### ISSUE THREAD

**Issue by TorbjornEliasson** [Megabit/Blazorise#2857]
We are today using Blazorise together with the Material provider. I would be great if you could clarify the relation between Blazorise  and Daemonite Material. 

1. Is Blazorise based on version 1 or 2 of Daemonite?
2. Is always Blazorise verified against the latest version of Daemonite or to a specific version?
3. Is there any considerations (related to Material) we should be aware of when Bootstrap 5 is supported in Blazorise.

Thanks for your great work so far. We will definitely buy a commercial license as soon as the first final version is released.

**Comment by stsrki** [comment]
Hi. 

1. We moved away from the Daemonite version because it is not maintained anymore. Currently, we're using a forked version done by the **djibe** that you can look at https://github.com/djibe/material
2. If there are no major changes I think you're free to use any minor 4.x version. If any issue comes along you can report it to us. We already got similar requests before.
3. Bootstrap 5 will be just another provider and Bootstrap 4 will still exist.

The plan is to have two packages.
  - Blazorise.Bootstrap - for Bootstrap 4
  - Blazorise.Bootstrap5

**Comment by tdashworth** [comment]
When will `Blazorise.Bootstrap5` be released?

**Comment by stsrki** [comment]
Bootstrap 5 is already released as a preview on our private MyGet feed. You can try it on https://github.com/Megabit/Blazorise#try-preview

Also, if you're going a preview route, it is advised to check the migration notes https://preview.blazorise.com/news/release-notes/095
