### ISSUE TITLE
Rename Link component

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#2875]
At the moment `Link` is a Razor reserved word and because of that, we cannot write it in a razor file without an Intellisense complaint. See #2424

So instead of `<Link To="#"></Link>` we always have to write it as `<Blazorise.Link To="#"></Blazorise.Link>`, which is tedious.

---

The alternative is to rename the Link to something else and proposals are

- `<Anchor To="/">Home</Anchor>`
- `<Hyperlink To="/">Home</Hyperlink>`

---

[![](https://api.gh-polls.com/poll/01FEZSJPACK4AYB7353AETNCV8/Anchor)](https://api.gh-polls.com/poll/01FEZSJPACK4AYB7353AETNCV8/Anchor/vote)
[![](https://api.gh-polls.com/poll/01FEZSJPACK4AYB7353AETNCV8/Hyperlink)](https://api.gh-polls.com/poll/01FEZSJPACK4AYB7353AETNCV8/Hyperlink/vote)

Something else? Write in the comment.

**Comment by CaiusJard** [comment]
Honestly? Neither. Instead we should be [lobbying Microsoft to allow aliasing of types (`@using BLink = Blazorise.Link ... <BLink ..`) so we can decide our own short format](https://github.com/dotnet/aspnetcore/issues/13090) rather than every single library our there having to rename and rename again its members to avoid conflict with other libraries and our own custom controls..

I'll carry on using Blazorise.Link until MS pull their finger out, or I'll make my own subclass BLink that does nothing other than inherit Blazorise.Link if I want to use BLink in markup

I don't like anchor so much because it's hard to find; if you're used to Link, typing Link and getting intellisense does at least bring up Hyperlink.. MS also guilty of inventing new namesv (NavLink) and I wish they wouldn't.. This "learn another new set of names for a new lib that does the same old thing" is exhausting.. Need to fix the cause, not patch the symptoms

**Comment by stsrki** [comment]
@CaiusJard I agree, but unfortunately, they're not very fast delivering a fix. See an open ticket https://github.com/dotnet/aspnetcore/issues/18685 from last year.

I like `Link` and I would like it to stay but I have no idea how soon the fix will come, or ever. Maybe the workaround is to leave it but only introduce the Anchor component that directly inherits from the Link?

**Comment by CaiusJard** [comment]
That, my mind, would be the least impact; i can imagine that a lot of people have used Blazorise.Link. Anchor could be introduced, and if ms ever allow @using X=Y, it can be deprecated in favor of an advice to either replace with <Link or add an alias to the global imports if they didnt want to change code

Personally i'd like to see case sensitivity mean something in rzr intellisense; <Link != <link as far as the syntax highlighter is concerned, so why not intellisense/have a "lowercase is html, PascalCase is componentry" distinction..
