### ISSUE TITLE
Blazorise.Snackbar.Constants accessibility level

### ISSUE THREAD

**Issue by Jimmys20** [Megabit/Blazorise#2997]
Hello, does this class have to be public https://github.com/Megabit/Blazorise/blob/master/Source/Extensions/Blazorise.Snackbar/Constants.cs? I believe this class is only used internally by Blazorise.

I ask this because it conflicts with my own Constants.cs class and I have to use alias in many places (using Constants = MyNamespace.Constants) to distinguish.

**Comment by David-Moreira** [comment]
Since you probably use Snackbar less then your own `Constants`, you can choose not to place `Blazorise.Snackbar` `namespace` under `_Imports.Razor` to avoid the conflict. You'll have to explicity reference / import `Blazorise.Snackbar` whenever you want to use snackbar on your files of course!

As for whether it has to be public or not. I'll leave that to be answered by @stsrki 
But since it's a static class, I'm not sure if it's intended to be a global configuration, the users can change.

As everything in c#, you should be able to manage library naming conflicts by using the appropriate `namespace` imports according to your needs.

**Comment by stsrki** [comment]
Unfortunately yes, it needs to be public. We have a separate component under the `Blazorise.Components` project that is dependent on Snackbar. And it also uses Constants. So it best to do as David said. Don't define it in `_Imports.razor`, but at the beginning of the `.razor` component where you have a Snakcbar.

Closing now.
