### ISSUE TITLE
RadioGroup binding not working

### ISSUE THREAD

**Issue by jgranger36** [Megabit/Blazorise#3025]
**Describe the bug**
When using the RadioGroup component, the child radio components do not trigger the change event to fire when options are selected. I get no value set to the bound property and if i use CheckValueChanged, the associated method never gets fired. 

here is my use of the component. 
```
                            <RadioGroup TValue="Option" Name="@product.Id.ToString()" @bind-CheckedValue="@SelectedOption">
                                            <Repeater Items="@product.Options" Context="option">
                                                    <Radio Name="@product.Id.ToString()" TValue="Option" Value="@(option)">@option.option</Radio>
                                                </Repeater>
                                        </RadioGroup>
```

I expect that when a radio button is selected as part of a RadioGroup, the RadioGroup @bind-CheckedValue would trigger the bound property to update. 

Additional context: This is inside of a Repeater component, so we have some nested iteration going on. The TValue is an object and not a generic type.

**Comment by stsrki** [comment]
I suspect the problem is in the Option being a complex object. Its value must be serialized to a value that can be bonded to radio value in the DOM. You have two ways to handle it.

1. Use something else to bind the option value, like int or string, and then manually map it to the Option.
2. override `ToString()` inside of Option object and then return some unique value.
