### ISSUE TITLE
DisposeAsync() causes Dispose() to not be called

### ISSUE THREAD

**Issue by FStolte** [Megabit/Blazorise#3037]
After updating from 0.9.3.6 to 0.9.4.4, we've had memory leak problems in our project. The memory dump suggested that it's the Blazorise.Snackbar component that is not cleaned up properly. After some digging I could pinpoint the issue to the new IAsyncDisposable support added in 0.9.4.

After a little bit of debugging I realized that on a component implementing both `IDisposable` and `IAsyncDisposable`, only `DisposeAsync()` seems to be called by the Blazor framework. Therefore, it is necessary to call `Dispose(true)` instead of `Dispose(false)` from `DisposeAsync()` in `BaseAfterRenderComponent` since there are sub-classes that only support synchronous disposing, like the Snackbar.

Additionally, I saw that in `CountdownTimer`, the `timer` variable is never disposed, only stopped. It seems that has nothing to do with my current problems, since it has already been missing in 0.9.3. Nevertheless, you might want to add that 🙂

**Comment by David-Moreira** [comment]
Hello,
Thank you for reporting this.
So for **0.9.4**, we'll explicitly fix the bug without changing the internals.

For **0.9.5** we'll take a look at reworking the internals. The suggested `Dispose(true)` does not seem right in the `DisposeAsync` context, as generally a call to this means, that a way to dispose the component asynchornously has been provided and there is not reason to do it synchronously or vice versa.

>"A good implementation pattern of the IAsyncDisposable interface is to be prepared for either synchronous or asynchronous dispose." 

This would mean that currently every component that inherits `BaseAfterRenderComponent` should provide both `Dispose `and `DisposeAsync`, and not doing so, leads to bugs like the one reported.

**Microsoft's guidelines:**
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync
![image](https://user-images.githubusercontent.com/22283161/139561172-416eda55-2cb1-4660-8b56-d6619f69b183.png)
https://github.com/dotnet/runtime/blob/035b729d829368c2790d825bd02db14f0c0fd2ea/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.cs#L297-L345

I was thinking, and I still have to run some tests, but it does not seem to make sense to implement the `IAsyncDisposable` at the BaseComponent level, as we are not needing to do asynchronous disposal and it is probably being called on most cases instead of the provided synchronous `Dispose` method, which we actually should call. 

So we should only implement it whenever it is really warranted.
![image](https://user-images.githubusercontent.com/22283161/139561124-f812bdfe-3c99-4623-928a-5132cf7c5927.png)
