### ISSUE TITLE
Documentation page width cut off content

### ISSUE THREAD

**Issue by puschie286** [Megabit/Blazorise#3112]
**Describe the bug**
The documentation info tables at the bottom cut off the description column when window with > 1262

**To Reproduce**
1. Go to any documentation page
2. Scroll down to the parameter table
(3. Maximize your window to ensure widht > 1262px ) 

**Expected behavior**
A normal layout

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2429036/141125090-3212a082-7eea-444e-a22a-2b1fae00d4ef.png)

**Additional context**
thought you are working on it because the problem has always existed

Tested on Chrome, Firefox, Edge

**Comment by stsrki** [comment]
Thank you for giving us a message. Unfortunately at this time, we don't plan to work on maintaining current documentation. The reason is that we have already done with the completely new web that will replace it. The release, along with the new 0.9.5, is planned for Nov 15 next week. It can be seen at https://preview.blazorise.com/.

**Comment by puschie286** [comment]
ah, great - thanks for mention it
