### ISSUE TITLE
First day of the week is incorrect

### ISSUE THREAD

**Issue by ebicoglu** [Megabit/Blazorise#3274]
**Describe the bug**
The first day is Tuesday which is incorrect.
Must be culture-specific or Monday.
Maybe related to https://github.com/Megabit/Blazorise/issues/1997
![image](https://user-images.githubusercontent.com/9526587/147827179-95b0d211-7acf-41af-985e-376f26293ea3.png)

**Comment by David-Moreira** [comment]
Hello @ebicoglu,
have you tried to use `FirstDayOfWeek` setting?
![image](https://user-images.githubusercontent.com/22283161/147827514-87001b3d-7b48-4871-86ff-98a10fc7d9e6.png)

In the meantime, I went to take a look at the translation since I knew I had seen this visually correct when localization is set to my native language which is Portuguese. I noticed the translations are jumbled up:
![image](https://user-images.githubusercontent.com/22283161/147827475-4154cefd-8d7b-4b56-a506-701315f050f6.png)

(Should be )

    "Monday": "Segunda-feira",
    "Tuesday": "Terça-feira",
    "Wednesday": "Quarta-feira",
    "Thursday": "Quinta-feira",
    "Friday": "Sexta-feira",
    "Saturday": "Sábado",
    "Sunsay": "Domingo",
(I can go ahead and correct the pt translations later...)
@stsrki  can you check if the same happens for other translations?

**Comment by sturlath** [comment]
The days are also shifted for icelandic https://github.com/Megabit/Blazorise/blob/447d4773575f1c1f2530d4189c93935ac4141133/Source/Blazorise/Resources/Localization/DatePicker/is.json

Mondays are shown as Sunday etc

**Comment by stsrki** [comment]
Yeah, it seems it is a copy-paste mistake. We'll fix it. @David-Moreira you can fix Portuguese
