### ISSUE TITLE
async Modal.Show()

### ISSUE THREAD

**Issue by muratyuceer** [Megabit/Blazorise#3287]
Hello, this question not about blazorise but I want to asked. Both methods below work to open modal. 
Which method should we use? Technically what is the difference?

```
                    <Button Color="Color.Secondary" Class="mr-1" Clicked="async () => await OpenNotificationModal()">
                        <Icon Name="IconName.Bell" />
                        Bildirimler
                    </Button>
```

VS

```
                    <Button Color="Color.Secondary" Class="mr-1" Clicked="OpenNotificationModal">
                        <Icon Name="IconName.Bell" />
                        Bildirimler
                    </Button>
```

**Comment by stsrki** [comment]
Using `OpenNotificationModal` without lambda should be preferred. That is if there are no custom arguments that need to be passed to the method.

I cannot find the source now, but I remember people reported problems with lambda expressions. If I recall it, it was something about memory leaks. Or was it about speed dropping down? 🤔

**Comment by David-Moreira** [comment]
I Also vote for without lambda.

I doubt there is that much of a difference, much less a memory leak because of that? That should be equivalent to setting up an anonymous method + async state machine behind the scenes which is a bit more work then without lambda as far as I persoanlly know.

If you're really into it you can see translations from c# to IL on this resource:
https://sharplab.io/

Altough there is not exactly for razor. But I remember there's some folder with the compiled razor file if you're curious what's generating behind the scnes.
It should be under :  obj/Debug/net5.0/Razor for net5. Now I don't know what they did to it on net6 as I cant seem to find it.

**Comment by stsrki** [comment]
They use source generators in net6 so those files are gone, unfortunately.

**Comment by stsrki** [comment]
I asked the same question on Gitter and here is the answer

![image](https://user-images.githubusercontent.com/900302/148361159-05a749d3-4fde-416c-aeb9-96712b6ea403.png)

So, yeah there is a little overhead. Closing now :)

**Comment by muratyuceer** [comment]
Thanks, for research more clear now, I will try to not use lambda
