### ISSUE TITLE
Unit testing using bUnit and Blazorise

### ISSUE THREAD

**Issue by baltazarO** [Megabit/Blazorise#3327]
I have a blazor app that uses blazorise. The page has a numericEdit blazorise component. I get a system.invalid operation exception when running a unit test. I am using testing files identitical to what you guys are using in your Blazorise/Tests folder.

Environment: 
Desktop PC with Intel Core i5 (x64 processor)
Windows 10
using Blazorise and Blazorise.Material 0.9.5.4
bUnit 1.4.15
.NET 6
EFCore SQLServer 6.01
Moq 4.16.1
xUnit

Steps to reproduce:
Create a bUnit test project, add in the BlazoriseConfig.cs file (from master branch). Get modules from blazorise for example JSFileModule.cs and anything else needed for BlazoriseConfig to compile. Make a unit test, render component and add these lines:

BlazoriseConfig.AddBootstrapProviders(Services);
BlazoriseConfig.JSInterop.AddNumericEdit(this.JSInterop);  

Run unit test. 

Expected result:
Tests run without exceptions

Actual result:
System.InvalidOperationException : Cannot provide a value for property 'JSModule' on type 'Blazorise.NumericEdit`1. There is no registered service of type 'Blazorise.Modules.IJSNumericEditModule'.

**Comment by baltazarO** [comment]
Still relevant

**Comment by stsrki** [comment]
@David-Moreira can you help?

**Comment by David-Moreira** [comment]
Hello,
The error is quite clear, there's a missing dependency that the container cannot find.

Latest release is 0.9.5, so it is advisable to copy from rel-0.9.5 branch instead. As you have copied a BlazoriseConfig with incorrect dependencies setup for that version.

Steps:
- Create new test project
- Download Bunit
- Download Blazorise 0.9.5 and Blazorise.Bootstrap 0.9.5
- Copy Blazorise.Config from Blazorise rel-0.9.5 branch and remove undeeded stuff
- Compile just to make sure everything is okay so far...
- Copy **NumericEditComponentTest.cs** as an example
- Setup Blazor project
- Download Blazorise 0.9.5 and Blazorise.Bootstrap 0.9.5
- Copy **NumericEditComponent.razor.cs** as it is the component being rendered/tested by **NumericEditComponentTest.cs**
- Make sure everything compiles and fix stuff if needed
- Run Tests..
![image](https://user-images.githubusercontent.com/22283161/149849799-6c8f35a7-1b76-42c5-a235-377dd0f07122.png)

**Comment by baltazarO** [comment]
Oh I need blazorise.bootstrap too?

**Comment by David-Moreira** [comment]
Oh, in my test I setup the Bootstrap provider, but It should work without the provider.
What we recommend is that you test with the provider you are using so the tests are faithful to your scenario.

**Comment by baltazarO** [comment]
Right I agree there. Now I got the "right" Blazorise config from rel-0.9.5 branch but now I am getting the error:

Bunit.JSRuntimeUnhandledInvocationException : bUnit's JSInterop has not been configured to handle the call:

    InvokeAsync<IJSObjectReference>("import", "./_content/Blazorise/memoEdit.js?v=")

Configure bUnit's JSInterop to handle the call with following:

    SetupModule("./_content/Blazorise/memoEdit.js?v=")

Does this mean I should get rid of this line: services.AddScoped<IJSMemoEditModule, JSMemoEditModule>();?

**Comment by David-Moreira** [comment]
No, you should not.
BUnit has a kind of "internal mock" for js interop, since it cannot actually do real javascript calls as it is not running in an actual browser environment.
You have to tell it how to mock any js calls that are done. In this case is telling you, how you could tell it to mock a javascript module import for out memoEdit.js

There are already a few examples, for example:
![Sem Título](https://user-images.githubusercontent.com/22283161/150043763-796383c6-bcfb-4fc3-a1ff-7f07ba1bf5d6.png)

Just base yourself on that one. Or you could also do it as BUnit suggests, it's the same end result: 
`SetupModule("./_content/Blazorise/memoEdit.js?v=")`

Let us know if you're still having difficulties. :)

We've only mocked what we needed for our current tests, so it's only natural that if you are testing different things there might be stuff that we haven't setup in ours.

**Comment by David-Moreira** [comment]
@baltazarO has this helped you move forward with your tests? Is this issue safe to close? :)

**Comment by baltazarO** [comment]
Yes. Thank you.
