### ISSUE TITLE
DataGrid: ArgumentNullException on select all

### ISSUE THREAD

**Issue by hillin** [Megabit/Blazorise#3442]
**Describe the bug**
In a DataGrid when `dirtyView` is `true` (e.g. when the `Data` property is set), using the column header of a `DataGridMultiSelectColumn` to select all will trigger an `ArgumentNullException` in [`OnMultiSelectAll`](https://github.com/Megabit/Blazorise/blob/261f8af6cace535f0195ad0aebd5dbf6569271bc/Source/Extensions/Blazorise.DataGrid/DataGrid.razor.cs#L901), because `viewData` is null.

**Comment by hillin** [comment]
I think it's also worth noting that we are using Virtualize + ReadData callback (i.e. `VirtualizeManualReadMode`), which does not make use of the `DisplayData` property, in whose getter the `viewData` is actually resolved.

**Comment by David-Moreira** [comment]
Hello @hillin 
We'll take a look at it. Just to make sure we can replicate.
It's Virtualize + ReadData + MultiSelect right? Nothing else of note? Because on our demo it seems to be working.
Are you setting the data to null and then trying to multi select all, is that it?

If you could post a simple sample we would appreciate it :)

**Comment by hillin** [comment]
Here is a small repro: https://github.com/hillin/BlazoriseIssues
Simply click on the mutliselect column header checkbox and you'll see the exception.

**Comment by David-Moreira** [comment]
Hello @hillin 
The repro does not throw any exception. However it is not selecting all the rows, yes.

**Comment by David-Moreira** [comment]
Nvm, it does throw it. I had it turned off... and for some reason the exception is somehow "swallowed", does not even crash the app O.O

Either you're right. We're using `viewData` field and it has not been calculated yet, since `DisplayData`, the property, hasn't been accessed. No idea why we didn't use `DisplayData` straight away, it assures the data is fresh.

Thanks for reporting. We'll fix it.
