### ISSUE TITLE
NumericPicker Step with decimals does not work correctly with culture

### ISSUE THREAD

**Issue by yggdrasil-tynor** [Megabit/Blazorise#3606]
**Describe the bug**
NumericPicker step component does not work correctly with Step < 1.0M after upgrading to Blazorise 1.0.

**To Reproduce**
<NumericPicker TValue="decimal?" DecimalSeparator="." Decimals="1" Step="0.1M" Culture="da-DK" @bind-Value="@SelectedValue" >

**Expected behavior**
Should step from 0 to 0,1 --> 0,2 --> 0,3. Instead it steps from 0 --> 0,1 --> 1,1 --> 11,10 etc.

The same issue occurs in the old NumericEdit component. In blazorise 0.9.* it worked correctly with Culture set. If I change to step 1.0 it works correctly again, so this is an issue with decimal steps and Culture. If i remove culture and use DecimalSeperator only it works correctly.

**Comment by stsrki** [comment]
The issue here is that `Culture="da-DK"` has a decimal separator as `","`, while internally we are working with a decimal separator as `"."`. I believe we have accidentally left the `Culture` parameter when we copied some code from NumericEdit while creating the NumericPicker. All localization settings should be able to set via `DecimalSeparator` and `AlternativeDecimalSeparator`, so Culture is not needed.

**Comment by yggdrasil-tynor** [comment]
@stsrki I see, that's also what i changed to. However it broke some of our stuff when upgrading to Blazorise 1.0. So maybe it should be noted in the "breaking change" migration guide :)

Thanks for the quick support and keep up the good work.

**Comment by stsrki** [comment]
One thing I could see where Culture can be used is on defining the alternative way for `DecimalSeparator`, `GroupSeparator`, etc. For example if `Culture` is defined but nothing else, NumericPicker would pick those settings and use them to display in edit mode.
