### ISSUE TITLE
Capturing data into modal fields.

### ISSUE THREAD

**Issue by GevorDanielyan** [Megabit/Blazorise#3640]
Hello everyone.

I have button, and when I click that button, opens a modal with some numeric fields.  For example -

```
<Field>

    <Button Color="Color.Dark" Clicked="@ShowModal" Outline>
        Refresh
    </Button>
    <Modal @ref="modalRef">
        <ModalContent Centered>
        <ModalHeader>
            <ModalTitle>Rates</ModalTitle>
            <CloseButton />
        </ModalHeader>
        <ModalBody>
            <Field>
                <FieldLabel>Bid:</FieldLabel>
                <NumericPicker TValue="decimal?" />
            </Field>
            <Field>
                <FieldLabel>Ask:</FieldLabel>
                <NumericPicker TValue="decimal?" />
            </Field>
        </ModalBody>
        <ModalFooter>
            <Button Color="Color.Secondary" Clicked="@HideModal">Close</Button>
            <Button Color="Color.Primary" Clicked="@HideModal">Save Changes</Button>
        </ModalFooter>
    </ModalContent>
    </Modal>
    
</Field>


@code {
    private Modal modalRef;

    private Task ShowModal()
    {
        return modalRef.Show();
    }

    private Task HideModal()
    {
        return modalRef.Hide();
    }
}
```

How can I fill the fields of that modal with the data read from the my gRPC backend? There is such an opportunity?

Thanks in advance.

**Comment by stsrki** [comment]
Since you have some external API I assume you also have a model that is returned from that same API? In that case, you create a variable:

`private SomeModel model;`

and bind to a field

`<NumericPicker TValue="decimal?" @bind-Value="@model.SomeField" />`

PS. This is more of a general Blazor question not necessarily linked to Blazorise. So it is better to start a discussion instead of an issue.

**Comment by GevorDanielyan** [comment]
Ok, I will start discussion about this.
