### ISSUE TITLE
Carousel slides are not uniform size

### ISSUE THREAD

**Issue by ghost** [Megabit/Blazorise#3641]
**Describe the bug**
Carousel slides with differing size content is causing the carousel to resize on the page

**To Reproduce**
Evident on the documentation page: https://blazorise.com/docs/components/carousel

**Expected behavior**
Probably expect the carousel size to be determined by default by the size of the largest element, that way the individual slides will always fit within the size of the carousel

**Comment by David-Moreira** [comment]
We haven't yet taken a look at this yet. But we've had this reported again recently on our discord, someone ("AluTheCrow" on discord) gave the temporary solution of setting "Height=Height.Is100" if you'd like to try.

**Comment by David-Moreira** [comment]
It looks like this is generally not supported out of the box.
![image](https://user-images.githubusercontent.com/22283161/175807439-ec42357c-87a8-4af3-981f-129fb3f18bf9.png)

I believe you always need to compute the height somehow. We can take this as a feature instead with an opt-in parameter since not every single user might want this behaviour.

**Comment by stsrki** [comment]
We should add a note in the documentation saying that slides need to have additional styles to make them all the same.
