### ISSUE TITLE
With an isolated CSS approach, Class Property does not work.

### ISSUE THREAD

**Issue by araxis** [Megabit/Blazorise#3659]
When using the isolated CSS approach, the element doesn't get the class and related CSS is not generated correctly by Blazor.

```c#
  <Div Class="test" Style="height:100px;width:100px" Border="Border.Is1">
        <p>Blazorise Div with Class property</p>
    </Div>

    <div class="test" style="height:100px;width:100px;border:thin">
        <p>div with Class property</p>
    </div>
```

css file

```css
.test{
    background-color:blue;
}
```

<table><tbody><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/1418779/161197126-9ddce68d-d147-4a82-9a08-d98f1556851e.png"></figure></td><td><figure class="image"><img src="https://user-images.githubusercontent.com/1418779/161197135-045eaf60-14a2-4ab1-be40-1e1038c004b7.png"></figure></td></tr></tbody></table>

**Comment by stsrki** [comment]
This is Blazor limitation and basically, every component library has the same problem. The problem is that CSS isolation is a compile-time process, so while Blazor is compiling it will apply unique IDs on an element and link it with CSS. This process works only with regular HTML elements.

For components, it cannot know where to place that ID and so it will not work. The only way to do it is to wrap a component with a `div` element and then target a selector based on that `div` element.

**Comment by puschie286** [comment]
you can also use it on blazorise components if you add ::deep before your style definition ( [Source](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-7.0#razor-class-library-rcl-support) ) - so it would be
`::deep .test { ... }`

you still need to wrap your component in a div
