### ISSUE TITLE
Bug drawing chart after show/hide dataset

### ISSUE THREAD

**Issue by Slashhhhh** [Megabit/Blazorise#3664]
On first load, chart is working fine but after using filters to show/hide a dataset it sums the values of all the shown datasets instead of overlaping them.

**To Reproduce**
Create a chart with atleast 3 different dataset, then show/hide atleast one and they will start to sum the values and stack over each other in the filter order (first at bottom, last at top)

**Expected behavior**
The datasets should not stack and be independent instead.

**Screenshots**
First load
![image](https://user-images.githubusercontent.com/102846382/161368193-b56044a5-eb78-400a-ba10-186755c6285b.png)

After manually hiding/showing one element (notice that the values are beuing summed)
![image](https://user-images.githubusercontent.com/102846382/161368226-fce8b992-f119-4772-9e65-ab6e7d0aa3a0.png)

Back to first load format using manual filters (continues to sum values)
![image](https://user-images.githubusercontent.com/102846382/161368259-1b861e51-75f6-4eb7-9918-5224fef46af6.png)

Refreshing the page fixes the issue until we use the manual filters again

**Comment by stsrki** [comment]
Can you post a code to reproduce the issue?

**Comment by Slashhhhh** [comment]
Here is some code as requested. Just follow the instructions above.

`<LineChart @ref="lineChart" TItem="double" />


@code {

    LineChart<double> lineChart;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await HandleRedraw();
        }
    }

    async Task HandleRedraw()
    {
        await lineChart.Clear();

        await lineChart.AddLabels(new string[] { "Red", "Blue", "Yellow", "Green", "Purple", "Orange" });

        await lineChart.AddDataSet(new LineChartDataset<double>
            {
                Label = "Randoms 1",
                Data = RandomizeData(),
                BackgroundColor = backgroundColors,
                BorderColor = borderColors,
                Fill = true,
                PointRadius = 3,
                CubicInterpolationMode = "monotone",
            });

        await lineChart.AddDataSet(new LineChartDataset<double>
            {
                Label = "Randoms 2",
                Data = RandomizeData(),
                BackgroundColor = backgroundColors,
                BorderColor = borderColors,
                Fill = true,
                PointRadius = 3,
                CubicInterpolationMode = "monotone",
            });

        await lineChart.AddDataSet(new LineChartDataset<double>
            {
                Label = "Randoms 3",
                Data = RandomizeData(),
                BackgroundColor = backgroundColors,
                BorderColor = borderColors,
                Fill = true,
                PointRadius = 3,
                CubicInterpolationMode = "monotone",
            });
    }

    List<string> backgroundColors = new List<string> { ChartColor.FromRgba(255, 99, 132, 0.2f), ChartColor.FromRgba(54, 162, 235, 0.2f), ChartColor.FromRgba(255, 206, 86, 0.2f), ChartColor.FromRgba(75, 192, 192, 0.2f), ChartColor.FromRgba(153, 102, 255, 0.2f), ChartColor.FromRgba(255, 159, 64, 0.2f) };
    List<string> borderColors = new List<string> { ChartColor.FromRgba(255, 99, 132, 1f), ChartColor.FromRgba(54, 162, 235, 1f), ChartColor.FromRgba(255, 206, 86, 1f), ChartColor.FromRgba(75, 192, 192, 1f), ChartColor.FromRgba(153, 102, 255, 1f), ChartColor.FromRgba(255, 159, 64, 1f) };

    List<double> RandomizeData()
    {
        var r = new Random(DateTime.Now.Millisecond);

        return new List<double> {
            r.Next( 3, 50 ) * r.NextDouble(),
            r.Next( 3, 50 ) * r.NextDouble(),
            r.Next( 3, 50 ) * r.NextDouble(),
            r.Next( 3, 50 ) * r.NextDouble(),
            r.Next( 3, 50 ) * r.NextDouble(),
            r.Next( 3, 50 ) * r.NextDouble() };
    }
}`

**Comment by stsrki** [comment]
I have run your example and I fail to see what is the problem. It seems to me that the chart is working as expected. When you hide a dataset then the chart will automatically adjust itself to accommodate leftover charts to take as much space as possible.

**Comment by Slashhhhh** [comment]
@stsrki please notice in the images above that after hiding and showing a random dataset, the value of the yellow line went from 42 (it's real value) to over 120, which is, if you do the math, the sum of all of the elements from the first image (40 + 41 + 42)

**Comment by stsrki** [comment]
You're right. I see it now. That's strange I must notice.

**Comment by vladioan96** [comment]
Hello,

I have the same bug and I found a workaround. 

## Quickfix (workaround)
This is the quick fix (add it in the `HandleRedraw` function after you call `await lineChart.Clear();`
```cs
LineChartOptions options = new()
{
    Scales = new()
    {
        Y = new()
        {
            Stacked = false
        }
    }
};

await lineChart.SetOptions(options);
```

## My complete working snippet

```cs
<LineChart @ref="lineChart" TItem="double" />


@code {

    LineChart<double> lineChart;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await HandleRedraw();
        }
    }

    async Task HandleRedraw()
    {
        await lineChart.Clear();

        LineChartOptions options = new()
        {
            Scales = new()
            {
                Y = new()
                {
                    Stacked = false
                }
            }
        };

        await lineChart.SetOptions(options);

        await lineChart.AddLabels(new string[] { "Red", "Blue", "Yellow", "Green", "Purple", "Orange" });

        await lineChart.AddDataSet(new LineChartDataset<double>
            {
                Label = "Randoms 1",
                Data = RandomizeData(),
                BackgroundColor = backgroundColors,
                BorderColor = borderColors,
                Fill = true,
                PointRadius = 3,
                CubicInterpolationMode = "monotone",
            });

        System.Threading.Thread.Sleep(100);
        await lineChart.AddDataSet(new LineChartDataset<double>
            {
                Label = "Randoms 2",
                Data = RandomizeData(),
                BackgroundColor = backgroundColors,
                BorderColor = borderColors,
                Fill = true,
                PointRadius = 3,
                CubicInterpolationMode = "monotone",
            });

        System.Threading.Thread.Sleep(100);
        await lineChart.AddDataSet(new LineChartDataset<double>
            {
                Label = "Randoms 3",
                Data = RandomizeData(),
                BackgroundColor = backgroundColors,
                BorderColor = borderColors,
                Fill = true,
                PointRadius = 3,
                CubicInterpolationMode = "monotone",
            });
    }

    List<string> backgroundColors = new List<string> { ChartColor.FromRgba(255, 99, 132, 0.2f), ChartColor.FromRgba(54, 162, 235, 0.2f), ChartColor.FromRgba(255, 206, 86, 0.2f), ChartColor.FromRgba(75, 192, 192, 0.2f), ChartColor.FromRgba(153, 102, 255, 0.2f), ChartColor.FromRgba(255, 159, 64, 0.2f) };
    List<string> borderColors = new List<string> { ChartColor.FromRgba(255, 99, 132, 1f), ChartColor.FromRgba(54, 162, 235, 1f), ChartColor.FromRgba(255, 206, 86, 1f), ChartColor.FromRgba(75, 192, 192, 1f), ChartColor.FromRgba(153, 102, 255, 1f), ChartColor.FromRgba(255, 159, 64, 1f) };

    List<double> RandomizeData()
    {
        var r = new Random(DateTime.Now.Millisecond);

        return new List<double> {
            r.Next( 3, 50 ) * r.NextDouble(),
            r.Next( 3, 50 ) * r.NextDouble(),
            r.Next( 3, 50 ) * r.NextDouble(),
            r.Next( 3, 50 ) * r.NextDouble(),
            r.Next( 3, 50 ) * r.NextDouble(),
            r.Next( 3, 50 ) * r.NextDouble() };
    }
}
````

## My analysis
The problem seems to be the [Stacked parameter](https://www.chartjs.org/docs/latest/axes/#stacking) from Y-axis. In Blazorise this is defined as `bool`, but in the official documentation seems that could also be used as a `string`. I tried to change it to `string` but had no effect.
I tried to figure out the solution in the Blazorise library by myself but I couldn't. Even though all the options parameters are parsed as null (so I assumed that the default config from chart.js lib would be used), this problem still appears. I check in debug mode to see exactly what parameters are set for each axis in chart.js. Here is a quick look:

![image](https://user-images.githubusercontent.com/78423351/162569237-90fdfc22-0a0c-4898-add3-7018e3b18eb3.png)

This happens after the chart is initialized in the chart.js (but the js from the Blazorise project) here:

![image](https://user-images.githubusercontent.com/78423351/162569300-b111b391-afa9-4df9-8343-25f685ac8d14.png)

The strange part (for me) is that the `stacked` parameter is not even defined here but the chart behaves like this is set to true.


@Slashhhhh hope that this will solve your problem for the moment
@stsrki hope this helps for future investigations

**Comment by stsrki** [comment]
Thank you @vladioan96. Your investigation will hopefully help us lead in the right direction.

**Comment by stsrki** [comment]
I've investigated more. Tried to remove every value from the options and from the dataset that we have and leave it to charts to set the default values. Nothing worked. Then I went and tried to reproduce the problem in codepen directly with chartjs library. An example can be seen at https://codepen.io/stsrki/pen/QWaxyPe

It seems that the problem was in `stack: "line"` on the datasets. If I remove it all works as expected. Not exactly sure but I think it is a leftover from v2.x that I forgot to remove from the dataset. Because I cannot find its mention in the v3.x documentation. But I need to investigate more to see is it safe to remove.

Also, since I have already gone and removed most of the default values from C# chart options I might also include that change in the patch. I think it is better in the long run, to leave to chartjs how they handle options once we supplied them. This way only what is defined will be used.

@vladioan96 @Slashhhhh @David-Moreira what do you think?

**Comment by Slashhhhh** [comment]
@stsrki is sounds good! @vladioan96 thank you for the workaround, it's a very simple solution while we wait for the fix.

**Comment by Kog008** [comment]
What do I have to do after setting `lineChart.Data.Dataset[i].Hidden = true` to actually hide the dataset?
I toggle the hidden value with a button.

**Comment by stsrki** [comment]
@Kog008  You need to `lineChart.SetOptions(newOptions)` before `lineChart.Update()`

**Comment by Kog008** [comment]
@stsrki Wow, thank you for your quick response! I have to think about that. Just by adding your line of code nothing is changing. I guess my understanding of blazor lifecycle is too limited atm. I tried something like

```
lineChart.Data.Datasets[0].Hidden = true;
lineChart.SetOptions(lineChartOptions);
lineChart.Update();
StateHasChanged();
```
I put the `StateHasChange()` to the `<LineChart @onchange="Refresh">` EventCallback as well, but did not work either.

Dont mind me, I discovered in the meantime, that your chart legend is already able to show/hide a dataset. I did not know that so far.

Thank your. I heavily appreciate your help and your work. Keep going. :-)
