### ISSUE TITLE
Datagrid details open logic

### ISSUE THREAD

**Issue by tacoWanneeJama** [Megabit/Blazorise#3704]
The administration of opened details of the datagrid is not consistent

**To Reproduce**
1. Go to https://bootstrap5demo.blazorise.com/tests/datagrid
2. Open details of "Irvin" and of "Gerald"
3. Got to page 2, and back to the first page of the datagrid

The same details should be opened, but only Gerald is opened. Why?

When after this, you collapse Gerald again, and go to page 2 and back to page 1, now Gerald is expanded again....

In my application I have a related problem:
I have a custom filter on the grid, that contains details. When this custom filter is changed all detail-grids are hidden.
I use the DetailRowTrigger mechanism to control the visibility of the details.

**Comment by stsrki** [comment]
It's just how the `DetailRowTrigger` is done in the demo app. We probably didn't anticipate that scenario and don't remember or persist the selected or opened row states. As far as I know, DataGrid should still be working as expected.

@David-Moreira

**Comment by David-Moreira** [comment]
Yes, we don't save detail row state across page navigation as far as I remember.
The reason why something is shown with detail row once you get back to the previous page, is because the row is selected and it is retriggered. 
I think it's this setting If I remember correctly: `DetailRowStartsVisible`

These two settings should give you some flexibility when playing with it.
![image](https://user-images.githubusercontent.com/22283161/162844925-abe677c8-4286-4d44-9418-5168143c164c.png)
Also It seems like it's missing on the docs, but you can also use the `ToggleDetailRow` 

Let us know if you're still having trouble.

**Comment by tacoWanneeJama** [comment]
I have the problem as mentioned at the and; when the custom filter changes, the details state is unsure.
This problem looks like the behavior of the demo application, so that's why I mentioned it.

I will have a look if I can write an example application that shows the same problem

**Comment by David-Moreira** [comment]
Yea I guess I kinda understand your problem, but an example application helps us get up to speed faster if you please. Thanks!

**Comment by tacoWanneeJama** [comment]
I made a testing application with about the same problem: 
https://github.com/tacoWanneeJama/BlazorApp1test
When you expand the last row and change the filter the expanded state of that row is NOT kept.
In my application this behaviour is for all rows, and not only the last row

**Comment by David-Moreira** [comment]
Hello,
In the case of your demo, you're just filtering the rows and the `DetailRowTrigger` is being evaluated to true correctly since you're keeping the currently detail rows in memory. 

------------
I'm going into a bit of a technical rant here so just skip to the proposed workaround if you're not interested:
What's happening is that the row was internally being re-initialized, therefore re-evaluating the `DetailRowTrigger` but with the information that the row is open, so it will toggle it, hiding it. 
In this case 
- If the row is initializing if should not be using info of disposed rows internal information.
- it shouldn't have re-evaluated `DetailRowTrigger` as the row already exists.
  - The idea is that is evaluates it only once on initialization (if `DetailRowStartsVisible` is set), and then only on row clicks or explicit api calls.
----------------
How we are using the information internally is not 100% correct, however, **you can use this as a workaround:**

```
    private bool OnDetailRowTrigger(DetailRowTriggerEventArgs<WeatherForecast> context)
    {
        context.Toggleable = false;
        bool result = RowIsExpanded(context.Item.Id);
        return result;
    }
```

By disabling `Toggleable`, it will not hide it on the DataGrid's re-evaluation as it will not act as a toggle, but instead just consider the **boolean** result from `DetailRowTrigger` which, since you're keeping track of which items should have detail in memory, makes sense to be disabled.
![image](https://user-images.githubusercontent.com/22283161/163889727-9ca7bfe5-ba3d-4873-9a9f-08295787bcc7.png)

**Comment by tacoWanneeJama** [comment]
https://user-images.githubusercontent.com/76042577/163933180-a375c6f0-68e1-420f-a418-4d4f04a788d3.mp4

This is how the problem shows in our application.

**Comment by tacoWanneeJama** [comment]
David,

I am sorry to report that the workaround does not work. Both in the example application and in our true application....

**Comment by David-Moreira** [comment]
> David,
> 
> I am sorry to report that the workaround does not work. Both in the example application and in our true application....

Are you sure? I had tested it. I'll try again, maybe I did something else and did not notice. Eitherway a patch should be available in a few days.

**Comment by David-Moreira** [comment]
You're right, **workaround** does not work, sorry bout that, I might've done changes to the Blazorise source code and tested incorrectly.
I was even trying to find you another `workaround` by doing some dumb dirty tricks with the `dataGridRef.ToggleDetailRow(row)` api, but it was already too much trouble to resync it.

Let's wait for the patch and please let us know how it goes by then. :) Thanks!

**Comment by tacoWanneeJama** [comment]
The updated version does work OK now. Thanxs!
