### ISSUE TITLE
DataGridColumn with button in DisplayTemplate onclick refresh the page and don't open modal dialog 

### ISSUE THREAD

**Issue by devrushnet** [Megabit/Blazorise#3709]
**Describe the bug**
DataGridColumn with button in DisplayTemplate onclick refresh the page and don't open modal dialog, Blazorise data grid 1.03

**To Reproduce**

	<DataGridColumn TItem="Employee" Field="@nameof( Employee.Id )" Caption="#" Width="60px">
		<DisplayTemplate>
			<button class="btn btn-warning btn-sm" @onclick="@(() => OnPrepareDoc())">
				<span class="oi oi-clipboard" aria-hidden="true"></span>
			</button>
			<button class="btn btn-warning btn-sm" @onclick="OnPrepareDoc">
				<span class="oi oi-clipboard" aria-hidden="true"></span>
			</button>
		</DisplayTemplate>
	</DataGridColumn>
	
						
	void OnPrepareDoc()
    {
		modalRef.Show();
    }

**Expected behavior**
Open modal dialog

**Comment by stsrki** [comment]
Can you try with

```
Task OnPrepareDoc()
{
	return modalRef.Show();
}
```

**Comment by devrushnet** [comment]
it's the same behavior

Task OnPrepareDoc() => modalRef.Show();

**Comment by David-Moreira** [comment]
Ah it seems like for some reason the page is being "postbacked". Now I don't know the exact reason, must be something to do with button trying to do a form submission post? We've had some issues in the past that we fixed.
Can you try switching your buttons by :

```
            <Button Clicked="OnPrepareDoc">
                Test
            </Button>
```

It should work.

**Comment by devrushnet** [comment]
the correct solution is:

	<DataGridColumn TItem="Employee" Field="@nameof( Employee.Id )" Caption="#" Width="60px">
		<DisplayTemplate>
			<Blazorise.Button Clicked="OnPrepareDoc">
				Test
			</Blazorise.Button>
		</DisplayTemplate>
	</DataGridColumn>

thanks

**Comment by stsrki** [comment]
It's because the default `<button>`  type is `type="submit"`, https://stackoverflow.com/questions/31644723/what-is-the-default-button-type#:~:text=For%20most%20browsers%20the%20default%20type%20of%20button%20is%20submit%20.&text=This%20attribute%20declares%20the%20type,submit%3A%20Creates%20a%20submit%20button.

In Blazorise Button will generate `type="button"`. And since datagrid edit fields are placed inside of the `form` for validation purposes, your `<button>` does the post back. My advice is to always stick with the Blazorise component whenever possible.
