### ISSUE TITLE
FileEdit freezes app and doesn't upload when MaxChunkSize is larger than 24*1024

### ISSUE THREAD

**Issue by janseris** [Megabit/Blazorise#3738]
**Describe the bug**
FileEdit _freezes the app for a moment (shows reconnecting attempt 1 of 8 etc)_ and _doesn't upload_ when MaxChunkSize is larger or equal than 24×1024.
It works well when 23×1024 or below.
I tried to speed up file upload because it is very slow (local Blazor app run in VS should have fast file upload I suppose) so I played with MaxChunkSize and both upload scenarios (buffered/non-buffered).
It is still slow and meanwhile I discovered this issue.

Btw. is actually the non-buffered code still buffered with default buffer size 20480? Is that what MaxChunkSize does?

**To Reproduce**
1. Try upload a file in the form

**Expected behavior**
File uploads with any "chunk size"

**Sample code - minimalistic repo**
[ESDRegistrace.zip](https://github.com/Megabit/Blazorise/files/8525855/ESDRegistrace.zip)

Video (expires after 30 days):
https://easyupload.io/c995oa

Blazor server
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 4.0
![image](https://user-images.githubusercontent.com/64279914/164337627-6a8cfb13-4f53-430c-91fc-5bfe9ba31410.png)

**Comment by stsrki** [comment]
I didn't test it, but I suppose the reason for slowness is that you're calling `StateHasChanged` in the Progressed event and that will trigger page re-render. So it has to render the entire page each time something is read. I would copy the following code and make it part of a sub-component so that it refreshes only that small part of the page.

**MyUpload.razor**

```cshtml
<Addons>
  <Addon AddonType="AddonType.Start">
      <AddonLabel>
          <span class="bi bi-file-earmark-text"></span>
      </AddonLabel>
  </Addon>
  <Addon AddonType="AddonType.Body">
      <FileEdit @ref=fileEdit
                AutoReset=false
                MaxChunkSize=24*1024
                Changed=OnSelectedFileChanged
                Written=OnFilePartReceived
                Ended=OnFileUploadEnded
                Progressed=OnFileUploadProgressChanged />
  </Addon>
  @if (FileUploadProgressVisible)
  {
      <Addon AddonType="AddonType.End">
          <AddonLabel Style="cursor: progress;">
              <SpinKit Size="1rem" Type="SpinKitType.Chase" />
          </AddonLabel>
      </Addon>
  }
</Addons>
@code{
  // other events handlers
}
```

The use it on the form as

```cshtml
<Field Horizontal>
    <FieldBody>
        <MyUpload ... />
    </FieldBody>
</Field>
```

**Comment by janseris** [comment]
@stsrki  So I have removed all status changes etc and 10 MB file upload still takes 2,5 seconds or 2 seconds (buffer 1 MB or non-buffered) which is slow on localhost.
Moreover, the issue with 24 * 1024 persists. The file does not upload when MaxChunksize is set to this value and it shows this (after 10 to 20 seconds for a 11 MB file):

![image](https://user-images.githubusercontent.com/64279914/164444323-3a4ecaf1-1198-4bba-b64f-8027095b5ce7.png)

**Comment by David-Moreira** [comment]
Hello @janseris 

You're using Blazor Server, quote from docs:

> In Blazor Server, JS interop calls are limited in size by the maximum incoming SignalR message size permitted for hub methods, which is enforced by [HubOptions.MaximumReceiveMessageSize](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.huboptions.maximumreceivemessagesize#microsoft-aspnetcore-signalr-huboptions-maximumreceivemessagesize) (default: 32 KB). JS to .NET SignalR messages larger than [MaximumReceiveMessageSize](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.huboptions.maximumreceivemessagesize#microsoft-aspnetcore-signalr-huboptions-maximumreceivemessagesize) throw an error. The framework doesn't impose a limit on the size of a SignalR message from the hub to a client.

https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#size-limits-on-javascript-interop-calls

So this explains your problem with the `MaxChunkSize` which basically transfers more information through `JsInterop` as you increase it, and certainly you've exceeded the default.


As for the reported slowness we can only try to keep improving upon it, we'll be taking a look at it and do some comparison tests vs native Blazor FileInput.

For the time being try playing with different `MaxChunkSize` values, my guess is that a higher value might actually be better because it cuts down on the number of js interop calls. Matter of testing if you don't mind. :)
