### ISSUE TITLE
AutoComplete with Multiple has problems showing the selected values when they are set through parameter

### ISSUE THREAD

**Issue by paulosdfigueiredo** [Megabit/Blazorise#3799]
**Describe the bug**
AutoComplete with Multiple values has some problems showing the correct text of selected values when they are set through parameter.

**To Reproduce**
Using [demo-bugs-page](https://github.com/paulosdfigueiredo/Blazorise/tree/demo-bugs-page)

0. Run Demo
1. Go to 'tests/bugs'
2. Click on 'Set Portugal & Croatia'
4. See the Selected Values being update, but AutoComplete only updates if you hover over it

another error

5. Clear selected values.
6. Select another country. ex: Spain
7. Click on 'Set Portugal & Croatia'
8. See the Selected Values being update, but AutoComplete only updates if you hover over it. And keeps Spain, showing 3 selected values.

AutoComplete single value is there as a Control showing the correct behavior.

**Expected behavior**
AutoComplete should update correctly the selected values when multiple is active.

**Comment by David-Moreira** [comment]
Seems similar to #3627
Will take a look.

**Comment by David-Moreira** [comment]
You're right pretty similar problem, certainly sovled with a `StateHasChanged` call in the right place. 
Also noticed that your exmaple wasn't running at all, did you make changes that are not commited? `SelectedTexts` internally throws due to being null, we're missing a null check there too. I had to add it to get to the problem you've reported. Which is something else to fix too.

**Comment by paulosdfigueiredo** [comment]
You are right, there is a problem with my AutoComplete, but somehow i am not getting that error. AutoComplete with multiple is not working correctly at start, but if I do the steps in the order I mentioned, by pressing the "Set" button, things go as I described.
