### ISSUE TITLE
Modal : Double click infite loop

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#3859]
Fix the issue detected by @bobbar

Analyse the proposed solution of remove the addition Show/Hide block
![image](https://user-images.githubusercontent.com/22283161/171071940-ccc290d0-e7e3-4772-8a08-8113bba3ef1a.png)

**Comment by Bobbar** [comment]
@David-Moreira 
I'm just having another look at this to confirm [my previous comment](https://github.com/Megabit/Blazorise/pull/3838#discussion_r884303770) regarding the show/hide calls.  

So calling Hide() or Close() on a modal just calls the internal Hide() which sets the close reason correctly as you mentioned [here.](https://github.com/Megabit/Blazorise/pull/3838#discussion_r884264004)

The "disco night" bug is caused by the closeable adapter creating a duplicate Hide call if the modal is closed before the animation Task.Delay finishes. So instead of calling Hide after the delay, it calls Show because the visibility state was already changed to false by the Close call caused by clicking off of the modal. So then is just runs in circles...

With the Show/Hide block removed, the duplicate calls don't occur. And the Close method in the modal still calls Hide internally, so the close reason is still set correctly.

**Comment by David-Moreira** [comment]
I see thank you for your help analysing. You had already applied the fix on a previous PR but we removed, if u want to go ahead and redo on a new PR. 
I'll make sure to retest on every provider, but by the looks of it, seems like we made it redudant.

**Comment by David-Moreira** [comment]
Closed by #3862
