### ISSUE TITLE
Modal form Visible property always false

### ISSUE THREAD

**Issue by tacoWanneeJama** [Megabit/Blazorise#3931]
When requesting if a Modal is yet opened, I investigate the Visible property, which should reflect the current state. I got stuck, because it is always false, even if the modal is opened.
When debugging I saw this strange behavior:
![image](https://user-images.githubusercontent.com/76042577/176894832-8106b3fe-22ea-472f-8962-a1fda33d7ff7.png)

The internal "IsVisible" does reflect the correct state, but the available property Visible claims a false, even when that is not true.

How can I get the correct value?

**Comment by stsrki** [comment]
This is kinda the expected behavior. You must remember that Blazor is like other similar SPA frameworks a declarative system. That means that most of the time parameters are used to tell the component of the new state changes. So, the `Visible` parameter should only be used to tell the `Modal` what the new value should be. Not the other way around. To get the visible value out of the modal you need to bind to the `VisibleChanged` event and then you will be able to retrieve the new visible state.

**Comment by tacoWanneeJama** [comment]
Ok, I can live with that
