### ISSUE TITLE
Autocomplete Component: InputField width isnt as wide as the displayed Displayed Field

### ISSUE THREAD

**Issue by ddsilasb** [Megabit/Blazorise#4031]
Hello,
our team found a bug while testing. The clickable InputField of the Autocomplete Component is more narrow than the actual Field is suggesting. So when you try to click on the right side of the Component it doesnt respond. 

I just want it to behave that everywhere it suggest to be clickable, it is clickable. 
![2e9f224a-2d99-4c7b-b29f-18e81ad27248](https://user-images.githubusercontent.com/104988332/182809053-8ab7ae72-468b-4459-8137-4dd5b38c1a24.jpg)

Our Code:

```
<Blazorise.Components.Autocomplete TItem="CustomRole" TValue="CustomRole" Data="@AllRoles" TextField="@(role => role?.Name)" ValueField="@(item => item)" Multiple @bind-SelectedValues="SelectedRoles" MinLength="0" CloseOnSelection="false" @bind-SelectedTexts="SelectedTexts">

</Blazorise.Components.Autocomplete>
```

**Comment by David-Moreira** [comment]
Hello,
Only the auto complete code might not be enough. As it probably works fine as a standalone otherwise we'd probably have noticed the bug.

Can you send the whole form / section code?

Don't forget that even your own styling can affect how components look.

**Comment by David-Moreira** [comment]
So I just now got to testing this on our own Docs App.

**Single Selection**
![image](https://user-images.githubusercontent.com/22283161/182963626-e5d39eb2-f5bf-4908-a7db-5a7c66e4b97a.png)
**Multiple Selection**
![image](https://user-images.githubusercontent.com/22283161/182963687-f2a73019-af20-4f62-af53-a3fae622f3cd.png)

So I can confirm that for multiple selection it does not take the whole width. Now I don't remember if there was a specific reason for this, but if there wasn't it seems like it should take up all the available space.

For now you could try applying 
`width: 100%;` to the input.
![image](https://user-images.githubusercontent.com/22283161/182963956-4ebb71f4-8709-4e0c-ab5a-f94e1cfca9f5.png)
But you'll notice that the input will move to the bottom instead of taking up the remaining space. If this isn't a problem it could be worth adding until we fix it on our side. Or you can just straight up fix it on your side if you're good with styling, haha.

Thanks for reporting.

**Comment by stsrki** [comment]
Note for future:

Adding 

![image](https://user-images.githubusercontent.com/900302/189866898-dbe46452-06aa-4cef-a034-5b0c5ba0f0ae.png)

and then `width: 100%` on an input seems to be working.
