### ISSUE TITLE
Docs: Breaking change for bUnit tests

### ISSUE THREAD

**Issue by cpdog** [Megabit/Blazorise#4158]
Upgrading to 1.1 from 1.0.6 breaks tests written with bUnit. 

To reproduce:

```
var ctx = new Bunit.TestContext();
ctx.Services.AddBlazorise();
ctx.Render(b => b.AddContent(1,"Hello"));
```

Previously this worked, but now an error is thrown that says
> System.InvalidOperationException: Cannot consume scoped service 'Microsoft.AspNetCore.Components.IComponentActivator' from singleton 'Bunit.Rendering.WebTestRenderer'.

This was introduced because of this change: 
https://github.com/Megabit/Blazorise/commit/aa5688d66b6ed00e387dcddbbf73bba86c95a7d6#diff-3c8fc6beb5f26f01a58f318ac148606b01cdc4e92660d046acb60b2435f77183

that changed the behavior of IComponentActivator from transient to scoped. 

This can be worked around by changing the test to add back the transient service. i.e.,

`ctx.Services.AddBlazorise().Replace(ServiceDescriptor.Transient<IComponentActivator, ComponentActivator>());`

Of course, this isn't a bug _per se_ for Blazorise, but I expect *many* people like me are writing tests using bUnit and would hit this issue.

**Comment by stsrki** [comment]
I agree this is not an issue with Blazorise, since IComponentActivator is primarily an internal component. And people can quickly `Replace` it with the DI of their choice.

The change was mainly because of our optimization with the new disposing system that handles the transient components and clears them from memory. Previously they would tend to hang, and memory leaks would happen. Changing IComponentActivator from transient to scoped was also needed for performance reasons.

**Comment by David-Moreira** [comment]
I have to agree with @cpdog 
I wouldn't say no, to a simple note somewhere on the docs, since that's the first place a developer should visit. 
Then the note can eventually point to the blog post with more in depth info.

**Comment by David-Moreira** [comment]
Simple note, should be available on next docs update. Closing issue.
