### ISSUE TITLE
FileEdit breakes files from 1.0.6 to 1.1.1

### ISSUE THREAD

**Issue by Mr-Pearce** [Megabit/Blazorise#4213]
**Describe the bug**
I have a project where i upload files that are then further processed on the server.

in 1.0.6 the upload was just fine.
in 1.1.1 some parts of the File are missing after upload. 
(I didn't test the versions between.
File upload on 1.0.6
![1 0 6](https://user-images.githubusercontent.com/13457314/196632430-35014b80-a515-4cf7-946d-8d07c14ae6fe.png)
File upload on 1.1.1 (Save image to your desktop as the preview in github is not working on the file)
![1 1 1](https://user-images.githubusercontent.com/13457314/196632539-edf139a5-dd74-4363-b3b9-fa70d0b628de.png)

**To Reproduce**
                  
      <FileEdit @ref="@fileEdit" Placeholder="Programm" Filter=".png" AutoReset="false" Changed="@OnFileChanged" />
```
@code {

        FileEdit fileEdit;
        async Task OnFileChanged(FileChangedEventArgs e)
        {
            var file = e.Files[0];
            // A stream is going to be the destination stream we're writing to.
            try
            {
                // A stream is going to be the destination stream we're writing to.
                using (var stream = new MemoryStream())
                {
                    // Here we're telling the FileEdit where to write the upload result
                    await file.WriteToStreamAsync(stream);


                    file.Position = 0;
                    using (var stream = File.Create("SomePath/test.png"))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
            }
            catch (Exception exc)
            {
                var message = exc.Message;
            }
        }
}

```

**Additional context**
Test system is an net 6 Docker mcr.microsoft.com/dotnet/aspnet:6.0

**Comment by David-Moreira** [comment]
Hello,

We need to better understand what code are you actually running, since you've posted invalid code:
![Sem título](https://user-images.githubusercontent.com/22283161/196802893-40308e5a-159d-4b1c-9607-f77048820899.png)

I changed the code to this:
![image](https://user-images.githubusercontent.com/22283161/196802973-ed549bb7-c6e3-4c5b-af86-49a9b78e493a.png)
Grabbed a random picture on the internet and uploaded:
![image](https://user-images.githubusercontent.com/22283161/196803117-fcd2e05b-7623-48f2-8e09-f662bf7f3acf.png)

It seems fine to me. But again I might not have tested it under the same logic/conditions as you...
So can you provide us with a repro?
Also can you make sure nothing else failed on your environment? Something that stopped the upload midway, etc...? There were no errors thrown?

**Comment by David-Moreira** [comment]
Hello,
I kept doing some more tests, and remembered to use your image. 
I found the bug, we'll fix it asap. 

Thank you for reporting.

**Comment by David-Moreira** [comment]
PS: we should release the fix in a  few days, but if you want an alternative, you can use the other available API, `OpenReadStream`

```
            using var stream = file.OpenReadStream( long.MaxValue );
            using ( var fileStream = File.Create( "SomePath/test.png" ) )
            {
                await stream.CopyToAsync( fileStream );
            }
```

**Comment by adamhathcock** [comment]
Glad this was found.  Just discovered this has really broken file uploads for me.  Can 1.1.3 come out sooner or do I need to workaround it somewhere else?

**Comment by adamhathcock** [comment]
Nevermind...just read the workaround.  Thanks!

**Comment by Mr-Pearce** [comment]
@David-Moreira Sry for the broken Code. I Just copied some lines from different methods together to make it simple...
Obviosly i didnt get something runable together 😓.
Glad that you could find it anyway 👍
