### ISSUE TITLE
I cannot install Blazorise in my Blazor server side app. I get the Error that "Microsoft.AspNetCore.Blazor" package could not be find

### ISSUE THREAD

**Issue by mut9bu** [Megabit/Blazorise#4218]
I have a blazor server side app that is working without problem. (Net Core 3.1). I tried to install Blazorise according the quick start page in https://blazorise.com/docs/start. As my server has no internet access I have downloaded the packages "Blazorise.Bootstrap 0.7.2" and "Blazorise.Icons.FontAwesome 0.9.2.5".

I can install the "Blazorise.Icons.FontAwesome" without Error. But if I try to install "Blazorise.Bootstrap" I get the Error

"NU1101: Unable to find package Microsoft.AspNetCore.Blazor. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, Package source"

I cannot find any package like "Microsoft.AspNetCore.Blazor". What should I do now?

Update1: I have found a package like "Microsoft.AspNetCore.Blazor.Templates 3.1.0-preview4.19579.2" but if I try to install I get Error

"Package 'Microsoft.AspNetCore.Blazor.Templates 3.1.0-preview4.19579.2' has a package type 'Template' that is not supported by project 'WebApplication7'"

**Comment by stsrki** [comment]
Those are really old packages, over three years old, and I suspect that Microsoft has unlisted them from NuGet.org. Any reason why you cannot try the newest packages?

**Comment by David-Moreira** [comment]
Hello @mut9bu 
If everything works and compiles locally, where you have internet access, then it's just a matter of trying to setup the same environment in the server.

But I'm not sure if that's your problem. Can you better elaborate?
I don't quite understand what are you trying to do. Are you trying to use VS or compile the solution in a server without internet access? Or are you having this problem on your location machine with internet access?

Because the error gives me the feeling that you are trying to set it up in an offline environment. If that's the case then you have to somehow make the packages available on the offline environment.

I had a similar requisite sometime ago, where my build server had no internet access.

If that is the case:
Easiest way is to clear your nuget global cache.
dotnet nuget locals all -c
Then on your local machine rebuild the project, this should restore every package from an online source and compile it successfully.

If it compiles successfully, then everything that's needed was downloaded and exists. You just need to make these same packages available on the server with no internet access.

You can now go to your local machine nuget location, and copy every package that's needed to the server. Since you've cleared the cache previously, most likelly the packages in the nuget location are all packages downloaded and required by the solution you just compiled.

You can locate it with this command
dotnet nuget locals all -l
The Nuget Global Packages Folder.
