### ISSUE TITLE
FilePicker 1.1.2 dropzone Ignoring .msi Files

### ISSUE THREAD

**Issue by Mr-Pearce** [Megabit/Blazorise#4224]
**Describe the bug**
The dropzone in the new Filepciker ignores .msi Files (exe files are working fine)

**To Reproduce**

1. Go to https://blazorise.com/docs/components/file-picker
2. Try putting an .msi file on the **drop files here** or filepath field
3. Nothing happens

**Expected behavior**
.msi should be added to the Picker.

**Additional context**
Blazorise 1.1.2

**Comment by David-Moreira** [comment]
Might have to do with this validation function:
![image](https://user-images.githubusercontent.com/22283161/197633519-9018e6b9-e251-42d1-9fd8-f9e8181993a3.png)
Will have to do some research, but basically this was put in there to avoid considering folders as files on drop for example. Apparently the `.msi` package type might not be discovered by the browser input api and so nothing happens.

I believe there's no workaround for now. We'll let you know once we have more info.

**Comment by David-Moreira** [comment]
So I was doing some testing with the regular `<input type="file" />` which nowadays supports drop natively.
It seems that it does not care whether its a folder or a file and just accepts it. Our `FileEdit` also follows this convention. Meaning that if you drop a folder on either of them it will just take it.

So when we developed this, I guess I just tought it made sense to check, I didn't think however there could be cases like this, where the browser api would not figure out the file type, therefore ignoring an actual file like what happened here.

So not sure if we can ever be 100% sure it's a file, maybe if we check the name for the existense of an extension and even then you could just have extensionless files for some reason..., maybe we could check size... or maybe we can just remove this check and leave it up to the developer to check if needed, either by using `Filter` or by checking `Size` etc... 

This way we make sure we don't end up ignoring certain files just because our detection logic is not 100% accurate, like what happened here... 
What do you think @stsrki
