### ISSUE TITLE
The Bar component is not working with the Maui&Blazor when refreshing the page.

### ISSUE THREAD

**Issue by rwecho** [Megabit/Blazorise#4251]
**Describe the bug**
Only Bar component error when refreshing Maui with F5. 

**To Reproduce**
1. Create the Maui & Blazor project
2. add Blazorise by the tutorial
3. add Bar component in the index. razor
4.  worked in the odd refresh and error in the even refresh

**Screenshots**
![image](https://user-images.githubusercontent.com/8048753/199150790-8f50b1db-44ef-4dfa-895f-0da38deb9230.png)

**Comment by David-Moreira** [comment]
Same problem as #4287

**Comment by David-Moreira** [comment]
Hello @rwecho
since letting js exceptions propagate was apparently provoking more issues then anything and always due to mostly external behaviors we can't control,

We've decided to make it so js exceptions are ignored now. While having the option to revert to the whole behavior.
https://github.com/Megabit/Blazorise/pull/5611

Would you be able to try this again? Feel free to reopen the issue if you still find difficulties with this.
