### ISSUE TITLE
(MAUI Blazor) An error occurs when force load

### ISSUE THREAD

**Issue by realLiangshiwei** [Megabit/Blazorise#4287]
**Describe the bug**

I'm creating an MAUI Blazor app with Blazorise, but I got an error when I call `NavigationManager.NavigateTo(NavigationManager.Uri, true);` method.

An error message like this: `JS object instance with ID 1 does not exist (has it been disposed?)`

I will get the error if I use Blazorise's components but not Microsoft native components

**To Reproduce**

The code is very simple:

```csharp
@page "/"

@inject NavigationManager NavigationManager

<h1>Hello, world!</h1>

<TextEdit @bind-Text="@text" /> not working with the blazorise component

@*<InputText id="text" @bind-Value="text" />*@  working with the native component


<button id="btn" class="btn btn-primary" @onclick="ReloadPage">Reload current page </button>

@code {
    private string text;

    void ReloadPage()
    {
        NavigationManager.NavigateTo(NavigationManager.Uri, true);
    }
}
```
**Expected behavior**

Here is the minimalistic GitHub repo: https://github.com/realLiangshiwei/MAUIBlazorWithBlazorise

**Screenshots**

![image](https://user-images.githubusercontent.com/16813853/201092826-f6452ee2-b960-4915-a8c9-aecc58cd497a.png)

Actually I don't know the reason, but I think you will have some idea, could you please take a look? thanks.

**Comment by David-Moreira** [comment]
Hmm not sure how we should handle this, or if we should. This should be handled by the .net framework in a consistent way instead.

In regular Blazor we get a proper `JSDisconnectedException` when navigating away, since the circuit was broken.
Which we can safely ignore.
![image](https://user-images.githubusercontent.com/22283161/201549828-b945c729-0da0-4ca6-93ef-ef0e19e9dba9.png)

In MAUI we get a regular `JSException` 
![image](https://user-images.githubusercontent.com/22283161/201549874-1f164456-de01-4263-8770-7fc044670e1a.png)

Maybe `MAUI` should throw the same `JSDisconnectedException` when the circuit breaks from navigating away.
Could I ask that you report this over at dotnet / maui repo with the repo/example you provided? 
If  you'd like we can report this ourselves instead.

Some similarity to:
https://github.com/dotnet/aspnetcore/issues/33336

**Comment by David-Moreira** [comment]
https://github.com/dotnet/aspnetcore/issues/45112

**Comment by DobkoALOS** [comment]
> [dotnet/aspnetcore#45112](https://github.com/dotnet/aspnetcore/issues/45112)

They moved the issue to the backlog milestone so it may take a long time until this will get fixed.

An easy (but bit nasty) quick fix on your side may be to also check for JSException in combination with a check if the exception message contains "disposed".

This would be minimal invasive and could fix this annoying problem in no time so al least we would be able to use blazor desktop without being limitated due to blazorise.

**Comment by David-Moreira** [comment]
Hello @DobkoALOS @realLiangshiwei 
since letting js exceptions propagate was apparently provoking more issues then anything and always due to mostly external  behaviors we can't control, 

We've decided to make it so js exceptions are ignored now. While having the option to revert to the whole behavior.
https://github.com/Megabit/Blazorise/pull/5611

By downloading the reproducible and updating to blazorise v1.6 the issue no longer happens.

Would you be able to try this again? Feel free to reopen the issue if you still find difficulties with this.

**Comment by realLiangshiwei** [comment]
okay, thanks, I will give a try
