### ISSUE TITLE
Datagrid virtualization with external source makes scrolling instable

### ISSUE THREAD

**Issue by TacoWannee** [Megabit/Blazorise#4289]
I saw, that scrolling a virtual Datagrid goes very jumpy sometimes. When using an external source it is never stopping to load the data:
![2022_11_11_110525](https://user-images.githubusercontent.com/108428600/201318551-cff77b82-dbf5-48a3-ab67-9821e197dcef.gif)

How to reproduce:
I used the example Blazorise project (latest version):
Changed row 90 to: `await Task.Delay(random.Next(100) + 200);` (extra delay of 200 ms)
at row 113 I inserted:
`Console.WriteLine($"Get from {e.VirtualizeOffset}, {e.VirtualizeCount} records.");` (to see what he is doing).

When scrolling a few rows it is OK, but when scrolling halfway you get this problem..

**Comment by David-Moreira** [comment]
Seems like it's getting confused, I'm still not sure if it's because of all the calls.

**Note to self:**
Taking a look at Steve's Quickgrid implementation, approach actually seems close to ours.

He did add an inherit delay and a specific commentary which is useful, the idea about increasing delay:
![image](https://user-images.githubusercontent.com/22283161/201550879-2361bf34-5f9f-4bad-b791-e21976c308ba.png)

**Comment by stsrki** [comment]
Delay seems like a good idea. Hardly that the user will maniacally hit the page button. Or is it 😅🤔

**Comment by David-Moreira** [comment]
Page button? This is `Virtualize`, the faster the user scrolls down the more requests are done in a sequence. And I did test more thoughrouly and it starts getting "jumpy" as reported.

**Comment by stsrki** [comment]
> Page button?

My bad, I misread the problem 😅
