### ISSUE TITLE
Add option to change DataGridNumericColumns default column filter input box to NumericEdit or NumericPicker

### ISSUE THREAD

**Issue by asser-dk** [Megabit/Blazorise#4374]
For Numeric Columns the default column filter input field is of type "text". Would it be possible to add a simple option to change that to "number" instead or even add the option to turn it into a default NumericPicker?

I know you can do that with a `FilterTemplate` but given that this column type is specifically for numbers it feels like an obvious addition :)

**Comment by David-Moreira** [comment]
@stsrki Could we do the same as in this pending PR, where we add a dedicated filter component for that type of column? 
In this case it would be the `NumericPicker` since that's also what we use internally for editting.

![image](https://github.com/Megabit/Blazorise/assets/22283161/5155404b-d3bd-49e4-9869-70e1a71b576d)

**Comment by stsrki** [comment]
> @stsrki Could we do the same as in this pending PR, where we add a dedicated filter component for that type of column? In this case it would be the `NumericPicker` since that's also what we use internally for editting.
> 
> ![image](https://user-images.githubusercontent.com/22283161/250115795-5155404b-d3bd-49e4-9869-70e1a71b576d.png)

Do you mean to have a new type of column? Like `DataGridNumericPickerColumn`? Or add a new parameter?

**Comment by David-Moreira** [comment]
> > @stsrki Could we do the same as in this pending PR, where we add a dedicated filter component for that type of column? In this case it would be the `NumericPicker` since that's also what we use internally for editting.
> > ![image](https://user-images.githubusercontent.com/22283161/250115795-5155404b-d3bd-49e4-9869-70e1a71b576d.png)
> 
> Do you mean to have a new type of column? Like `DataGridNumericPickerColumn`? Or add a new parameter?

Well in this case I refactored the new celledit for select such that it was a more agnostic and reusable component, and reused for filter.
But bottom line is to make it so that if a numeric column shows up we use a numeric Picker and not a textedit like we're doing. I don't see why you are saying that would be a new column since the exiting numeric column already uses numeric Picker

**Comment by stsrki** [comment]
@David-Moreira can you look into this if you think there is enough time before 1.3? Or we will move it to the next milestone.

**Comment by David-Moreira** [comment]
I can try over the next days,
