### ISSUE TITLE
Card was made BaseComponent instead of BaseContainerComponent causing loss of ColumnSize in 1.2

### ISSUE THREAD

**Issue by adamhathcock** [Megabit/Blazorise#4582]
**Describe the bug**
Card lost ColumnSize

**Expected behavior**
Card to have ColumnSize

**Additional context**
Might have lost others.

Does Card not need it?  Using Bootstrap4 but seems universal.

**Comment by stsrki** [comment]
We made a lot of changes around the columns and rows, and one of the changes was that Card no longer will have direct access to the column sizes. I must admit that I have failed to mark it obsolete instead of moving it completely. Before I removed I checked for Bootstrap documentation if there is any mention of assigning `col` to the `card` element. There was none.

Tl;Dr Sooner or later the feature would probably go away, but I should have first made it obsolete. 

---

PS. I recommend to always arrange components inside of Row/Columns.
