### ISSUE TITLE
Issue with the datagrid scrolling

### ISSUE THREAD

**Issue by ItsTahaRehman** [Megabit/Blazorise#4601]
In the datagrid with virtualize when im scrolling to the end of the table then it behaves wrongly , it moves the scroll back to the top

https://user-images.githubusercontent.com/95471572/218459214-1570276b-46f0-4d9e-9ada-276321a77e51.mp4

this is the code I'm using for the datagrid read data function 

![image](https://user-images.githubusercontent.com/95471572/218459353-ed6c8a04-8d38-4551-b10b-5c0850830b9b.png)

I'm also using the latest blazorise version

**Comment by stsrki** [comment]
Can you give us more info? What provider do you use?

**Comment by ItsTahaRehman** [comment]
@stsrki can you pls let me know what do u mean by provider ?

**Comment by ItsTahaRehman** [comment]
@stsrki im using the bootstrap provider

**Comment by David-Moreira** [comment]
@ItsTahaRehman  Actually for these kind of issues, we really want/need a reproducable if that's possible. Would you be so kind as to provide us with a repro? Thanks!

**Comment by FranKieSator** [comment]
Hello,

I'm colleague of  @ItsTahaRehman . We've found the issue - it s caused when we reference jquery library (for some other JS code we use).

We tried to use version jquery 3.6.3 (latest) as well as 3.5.1 (mentioned https://blazorise.com/docs/start).

I wonder if there is any issue with using jquery together with Blazorise? or can we use jquery, which is inside Blazorise? If so, how to reference it?

Isuess we have when we reference jquery:
- scrolling in datagrid is chaotic and jumping (because it calling OnReadData multiple times)
- in another screen where we render some dashboard tiles (tens of them):
   - with jquery reference, it take over 30econd to render(display)
   - without jquery, it takes like 3seconds to render

**Comment by David-Moreira** [comment]
Hello @FranKieSator 
We still list the javascript dependencies as they are part of the dependencies of the bootstrap css framework,
However our implementations are adapted to work with c# mostly and as such we've found out that everything works pretty good without the javascript dependencies, we have our own websites deployed without them.

So, unless you're explicit adding these for some specific reason, you should be able to remove them:
```
<!-- These are the standard js dependencies this provider tipically dependes upon, but Blazorise deems these as optional as Blazorise Components should work correctly without these  -->
	<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
```
