### ISSUE TITLE
Solution hangs when trying to load. Is it time to break up solution file between source and demos?

### ISSUE THREAD

**Issue by dlandi** [Megabit/Blazorise#4637]
I downloaded the Blazorise repo. I've updated Visual Studio to the latest 17.5.1. 

Unfortunately, the IDE hangs before completing the load. (I have 128 gigs of RAM)

![image](https://user-images.githubusercontent.com/3196088/222166601-838da0b2-a433-4ba8-ac84-a64ccea8e51a.png)

Would you consider breaking this solution up into at least "source" and "demo"? maybe move demos into separate repo so there are no project dependencies involved (but instead used nuget pkg dependencies).

Thanks for listening.

**Comment by stsrki** [comment]
> Would you consider breaking this solution up into at least "source" and "demo"? maybe move demos into separate repo so there are no project dependencies involved (but instead used nuget pkg dependencies).

That would not work for us because we use demos for internal testing. Having them on NuGet would make it almost impossible to do anything. Especially large refactors can happen often.

---

To fix the loading error, I can only advise trying with a different VisualStudio. Instead of preview, use the RC version.

**Comment by dlandi** [comment]
No I am using VS 17.5.1 version, which is the official release.

**Comment by David-Moreira** [comment]
I think it's one of those things where you have to go ahead and clear vs cache.

**Comment by David-Moreira** [comment]
@dlandi were you able to solve the issue?

**Comment by David-Moreira** [comment]
I just did a fresh windows install and VS install on my machine, full solution loads just fine.

If the quantity of projects are an issue for some reason an option is to:
- build via the command line
- setup a solution filter with only the projects you want to view/work on

Personally, I have worked on **Blazorise** before with an older i5 cpu with just 4 cores / 4 threads, and having a local solution filter without demos, test projects, docs helps with performance and loading times if that's in any way an issue.

I will assume the issue has been solved and close it, let us know if otherwise.
