### ISSUE TITLE
webassembly template

### ISSUE THREAD

**Issue by mikepasoglou** [Megabit/Blazorise#4643]
I have installed in VS2022   the Blazorize templates.
I have create a new Blazorize   template  webassembly 

The app it is not running .  What have I do wrong ? 
Please inform me 

Thanks in advanced 
MIchalis Pasoglou

**Comment by stsrki** [comment]
It would be impossible to know what is wrong if you didn't give us more information. Can you upload your project?

**Comment by David-Moreira** [comment]
@mikepasoglou were you able to get it working?

Otherwise we will need more information. We would really appreciate the following:
- Uploading the project to github
- Giving us information on the actual choices you used in the Blazorise Template
- The actual compile error
- Any other thing you might find relevant to help us troubleshoot

Thanks!
