### ISSUE TITLE
Async/await support for NavigationAllowed in Steps component

### ISSUE THREAD

**Issue by SvetlanaIo** [Megabit/Blazorise#4688]
Hello!
I have the following task related to Steps. I must make it possible to go to the next step only if the form is valid. This works fine while i dont use async validators.
I would really like to have support for asynchronous methods. Like example below.

```
  async Task<bool> NavigationAllowed(StepNavigationContext context)
  {
    bool result = true;
    if (context.CurrentStepIndex == 1 && !await _validation.ValidateAsync())
      result = false;
    return result;
  }
```

**Comment by stsrki** [comment]
We can try to add an async callback in the following milestone if there is enough time. In the meantime, we're open to any contribution if you have some time to spare.

**Comment by stsrki** [comment]
@David-Moreira, do you think we should do this change in 1.5? It is kinda a breaking change for the user if it suddenly stops working as an async. And if we introduce a new `NavigationAllowedAsync,`, we go against our naming guidelines without the `*Async` suffix.

**Comment by tesar-tech** [comment]
Unfortunately, the current state of the `Steps` component has limitations that prevent the desired functionality.  

The main challenge arises from the two-way binding and multiple ways to change the actual page. This problem stems from the getter of `SelectedStep`, where the `NavigationAllowed` function is invoked.  

Making the `NavigationAllowed` function asynchronous prevents its calls from within the getter.  

While `NavigationAllowed` can be invoked from methods like `NextStep`, `PreviousStep`, and `SelectStep`, this does not solve the issue for cases where someone attempts to change the step using two-way binding (by modifying `selectedStep` in `@bind-SelectedStep="selectedStep"`).  

In its current form, two-way binding allows for certain flows that cause desynchronization between the parameter and its value set by the parent component. In the `@bind-SelectedStep="selectedStep"` scenario, `selectedStep` might differ from `SelectedStep` when navigation gets blocked.

Additionally, `NextStep`, `PreviousStep`, and `SelectStep` don't do the job as their names suggest because again - navigation can be blocked..

## Proposed Solutions:

- Rename `NextStep`, `PreviousStep`, and `SelectStep` to `TryGoToNextStep`, `TryGoToPreviousStep`, and `TryGoToStep`. These would be asynchronous and return a value indicating success.  
- Remove two-way binding entirely, as it cannot reliably work with `NavigationAllowed`.  
  - Replace `SelectedStep` with `InitialStep`.  
  - Keep `SelectedStepChanged` as it is.  
- Call the `NavigationAllowed` function within `TryGoToStep`.

**Comment by stsrki** [comment]
> * Rename `NextStep`, `PreviousStep`, and `SelectStep` to `TryGoToNextStep`, `TryGoToPreviousStep`, and `TryGoToStep`. These would be asynchronous and return a value indicating success.

The `NextStep`, `PreviousStep`, and `SelectStep` are already asynchronous. So I assume we only need to add check for `NavigationAllowed` before setting the `SelectedStep` internally. Now, we can also make them return `Task<bool>` instead of `Task.` The user can check on their side to see if the operation was successful.
