### ISSUE TITLE
Tab Component - function SelectTab("name") not working

### ISSUE THREAD

**Issue by 274188A** [Megabit/Blazorise#4699]
**Describe the bug**
Tab Control's function `SelectTab` when used in code behind on a self host blazor WASM app does not change the tab selected.

**To Reproduce**
Steps to reproduce the behaviour: - see github repo [here ](https://github.com/274188A/TabBugDemo) that reproduces the bug

**Expected behaviour**
Tab renders according to tab name passed into function `SelectTab`

**Comment by stsrki** [comment]
There are several things that could be improved with your code.

First, you must remember that Blazor works in a declarative way. When you say `SelectedTab="one"` Blazor will always set/reset SelectedTab to a defined value. You need to use two-way binding so that selected tab state is always in sync, eg `@bind-SelectedTab="@selectedTabName"`.

Second, `SelectTab` method is async. So it must be available.

Here is the full working code

```razor
<Button Color="Color.Primary" Clicked="SelectTabTwo">Click to Select Tab Two</Button>

<Tabs @bind-SelectedTab="@selectedTabName" @ref="tabsControl" Pills>
    <Items>
        <Tab Name="one">
            One
        </Tab>
        <Tab Name="two">
            Two
        </Tab>

    </Items>
    <Content>
        <TabPanel Name="one">
            ONE CONTENT
        </TabPanel>
        <TabPanel Name="two">
            TWO CONTENT
        </TabPanel>
    </Content>
</Tabs>
@code {
    string selectedTabName = "one";

    private Tabs tabsControl;

    private async Task SelectTabTwo()
    {
        await tabsControl.SelectTab( "two" );
    }
}
```
