### ISSUE TITLE
DatePicker DateChanged event not working on dateremove 

### ISSUE THREAD

**Issue by danik121** [Megabit/Blazorise#4760]
**Describe the bug**
DatePicker DateChanged event not working on date remove .
If I use "backspace" or ctrl+a del event it will not fire. If I click on the tab after deleting it works.
In my case I delete the value and then click save. But changes are not saved. View value is changed

It worked on version 1.2.0

**To Reproduce**

```
<DatePicker DateChanged="@DateChanged" TValue="DateTime?" Placeholder="dd/mm/yyyy" ElementId="EndDate" Size="Size.Small" DisplayFormat="dd/MM/Y" Date="@EndDate" />

    private void DateChanged(DateTime? dateTime)
    {
      EndDate = dateTime;
    }
```

**Expected behavior**
Trigger change event after every change

**Comment by tesar-tech** [comment]
I cannot reproduce the bug. Maybe it has been fixed in the meantime.

I understand from your description that the submit event on the form or the click event on the button appears **before** the `DateChanged` event, but that's not happening in my case.

I have tested it on WebAssembly, Server, with and without a form, using the new Blazorise version as well as version 1.3, and I still cannot reproduce the issue.

If you're still experiencing the bug, could you please provide more information? Is the issue still present?

**Comment by danik121** [comment]
@tesar-tech  i think it was fixed
