### ISSUE TITLE
ModalProvider control displays other elements when printing in fullscreen mode

### ISSUE THREAD

**Issue by zhaofenglee** [Megabit/Blazorise#4936]
After adding a button and opening ModalProvider using Demos/Blazorise.Demo/Pages/Tests/DataGrid/DataInMemoryPage.razor, when I click ctrl+P to print, the displayed elements are not correct.

The following code can reproduce the issue.

https://github.com/zhaofenglee/Blazorise/commit/bf5e9483f55912b80e6713b7e3f77b1f157d9570

![image](https://github.com/Megabit/Blazorise/assets/111716814/c3b13d6f-3de9-4754-81e0-6640c12c021d)

**Comment by David-Moreira** [comment]
Hello @zhaofenglee 
It seems like the table gets offset for some reason when the modal is on top full screen and it gets printed like that. 

I'm not sure where the issue lies, I don't see any issue with our css. Might be something with how printing gets handled, I have to admit, I don't know. @stsrki any ideas?

Anywho, it's such an edge case, that if you have the requirement for the fullscreen Modal page to be printed, I would honestly fix it by either
1. Applying a **media print** that hides the datagrid.
2. Manage the DataGrid visibility with a bool flag or class (style=display:none)

I guess 1 would be the most elegant.
https://developer.mozilla.org/en-US/docs/Web/CSS/@media
![image](https://github.com/Megabit/Blazorise/assets/22283161/48d9c895-8119-4846-b1af-8bb1679375c4)

**Comment by zhaofenglee** [comment]
hi @David-Moreira

Thank you very much for the suggestion. Use the class "d-print-none" to hide elements that do not need to be printed.

![image](https://github.com/Megabit/Blazorise/assets/111716814/5c06a8a7-15d0-48a5-b666-25dab925e437)

**Comment by David-Moreira** [comment]
> "d-print-none"

Great! I didn't know bs had print specialized classes. 

Thanks for letting us know!
