### ISSUE TITLE
DataGrid change Editable for some collumns dependant on insert/ update

### ISSUE THREAD

**Issue by tacoWanneeJama** [Megabit/Blazorise#4946]
I have a DatGrid with 2 columns. While inserting I want both fields to be editable. When updating I want 1 of the input fields to be fixed (readonly)
I can not fiend a way to achieve tis now. Inside the Editable field we can not use the context now.
The only alternative I see now is making my own custom input forms, but that would be a lot of extra code to maintain...

**Comment by David-Moreira** [comment]
Hello @tacoWanneeJama 

Can you try using **EditState**
By checking `DataGridEditState.New` and `DataGridEditState.Edit` you can make the decision to make the fields readonly or not accordingly.

**Comment by tacoWanneeJama** [comment]
Thank you, I expected this property on row level (in context), but this does work oké.
But only when changing the __Readonly__ property. If I try this logic on the __Editable__ property than the other column is not editable any more....

**Comment by tacoWanneeJama** [comment]
I se that this as a duplicate of: #1380

**Comment by David-Moreira** [comment]
> > Thank you, I expected this property on row level (in context), but this does work oké. But only when changing the **Readonly** property. If I try this logic on the **Editable** property than the other column is not editable any more....
> 
> Right `Editable` controls exactly that, whether it shows or not on the Edit modes. I don't see any other way then overriding the `EditTemplate` currently.

Actually let me get back to you on this one. I might be giving you the wrong information. I was double checking and it might happen to work partially how you want it to.
If `Editable=false` and the column is `Displayable` then the column should still render as **"readonly"**(not exactly readonly though) it renders using the `DisplayTemplate` instead of the `EditTemplate`. But I can double check later.

**Comment by David-Moreira** [comment]
Ah it's inline edit mode that still renders the column value if it's displayable. But it won't be editable.
![image](https://github.com/Megabit/Blazorise/assets/22283161/e84518a3-5510-478e-aa2a-69391ff0c524)
![image](https://github.com/Megabit/Blazorise/assets/22283161/d909aba7-8157-4bc2-b3bf-23efa7fc488c)

The other two existing edit modes will not render it at all.

@stsrki What do you think? I'm not sure this is consistent. I understand we might still show in Inline Mode because it's directly below the column. But maybe it should be the same across all three versions, and leave the user to control it with `Displayable` + `Editable`?

**Comment by stsrki** [comment]
I think we had the same discussion a long time ago. The conclusion was that the column is better to be shown in inline mode. It is made to be shown because we are only editing some fields, and others are displayed so that the UI doesn't get disrupted too much. They are also visible as a piece of additional information to the user while editing the row.

**Comment by David-Moreira** [comment]
> Thank you, I expected this property on row level (in context), but this does work oké. But only when changing the **Readonly** property. If I try this logic on the **Editable** property than the other column is not editable any more....

Also there's a shortcut by using `CellsEditableOnNewCommand` | `CellsEditableOnEditCommand`. You can just define a boolean for each of the EditStates. Just, again, it won't render the field at all in that case for the `EditMode.Form` and `EditMode.Popup`.
![image](https://github.com/Megabit/Blazorise/assets/22283161/3b1efac2-9bb2-48d0-8698-949f2f8acfcb)

**Comment by David-Moreira** [comment]
> They are also visible as a piece of additional information to the user while editing the row.

This is exactly what the user is looking for as I see it. But thing is, it won't render at all in **Form** or **Popup** as opposed to **Inline**.

**Comment by stsrki** [comment]
Because in Edit and Popup mode we don't need to worry about the table structure. The entire form in Form mode spans the table's entire row. Similar in Popup mode. It shows in a modal, so again we don't need to worry about the table structure.

**Comment by David-Moreira** [comment]
I get it. But you could still **render a blank column and it would be consistent, all modes not rendering a value.**

But I get, that since it's already there, it's preferable to render **the value** instead of a **blank column**, or so we think. Just that I would argue the behavior isn't the same across all of them by default.

**Comment by David-Moreira** [comment]
> I get it. But you could still **render a blank column and it would be consistent, all modes not rendering a value.**
> 
> But I get, that since it's already there, it's preferable to render **the value** instead of a **blank column**, or so we think. Just that I would argue the behavior isn't the same across all of them by default.

Let's imagine I would take advantage of using the 3 modes available in the DataGrid and give them to my end user. So he would just choose which mode he wants to use at a given time.

The user would have a different experience from the data that's presented to the user between **Inline** vs **Form** and **PopUp**. And I'm not talking about layout, because that's expected to be different. I'm talking about data presented according to DataGrid configuration. 
He would see the value in  **Inline** and then not see it in **Form** and **PopUp** given the same configuration.

**Comment by stsrki** [comment]
Yes, I can see where you're going with it. We could indeed hide the display value in Inline mode. But, IMO that would look weird. If I as a user go and edit some fields in a row, I would expect to not hide other values.

**Comment by David-Moreira** [comment]
Or we could do the other way. Display value in **Form** and **Popup** mode if `Editable=false`?

Users could override `Displayable` to make it not render at all instead. But I can understand if that's a big breaking change at this time and not worth it.

**Comment by David-Moreira** [comment]
**SMH**

I just noticed we have exactly what @tacoWanneeJama is looking for... 
I assumed we didn't have ReadOnly implementation in the column as I didn't remember this Parameter. Apologies!! This does give way more flexibility, even if how it gets rendered isn't consistent across the 3 modes.

@stsrki in this case, I don't think there's a point in us even thinking of a big breaking change like this. Enough flexibility is provided.

@tacoWanneeJama please try
![image](https://github.com/Megabit/Blazorise/assets/22283161/6f82ab46-7530-44ea-82b0-8fe2099c5c7e)
![image](https://github.com/Megabit/Blazorise/assets/22283161/4bd01523-28a9-4f7c-be16-fbe83106333c)

**Comment by tacoWanneeJama** [comment]
I now have:
```
        <DataGridNumericColumn TItem="ReporterRemark"
                               Field="@(nameof(ReporterRemark.Id))"
                               Caption="Code"
                               Editable="true"
                               Readonly="@(_grid.EditState != DataGridEditState.New)">
````
I think it would be nicer if I could use the `@context` instead of the reference to the grid.

**Comment by David-Moreira** [comment]
> Editable="@(_grid.EditState == DataGridEditState.New)"

I will go ahead and open an issue for that based on what've you said. From what I tested actually, Newing up was throwing when evaluating the `EditState` in the `Editable` parameter. We will have to investigate. It will be low priority as there are valid alternatives.

You should be able to achieve what you're trying in that example with :
`Editable CellsEditableOnNewCommand CellsEditableOnEditCommand=false Readonly=false`

As for the `@context` matter I don't think it makes sense to add that redudancy. I know it sometimes feels more elegant in certain cases, but it's an integral part of Blazor to get a reference to a component and make use of it's publicly available properties/methods if needed, specially in more complex and advanced components like `DataGrid`.

**Comment by David-Moreira** [comment]
I will go ahead and close this issue as I believe you have viable alternatives.

Please take note that another one was open for the bug that you've found.
