### ISSUE TITLE
Do the Blazorise tags have no prefix to identify them?

### ISSUE THREAD

**Issue by Tony20221** [Megabit/Blazorise#4950]
Do the Blazorise tags have no prefix to identify them?
How do I identify what is a Blazorise component vs not?

**Comment by stsrki** [comment]
No. We at Blazorise are against prefixes as we believe they introduce noise to the code. We want our syntax to be as easy as possible to read and write. That is something that we're proud to have. Adding prefixes would go against our guidelines.

> How do I identify what is a Blazorise component vs not?

Well, every component that starts with an Uppercase, or that doesn't have any prefix, can be considered as Blazorise component...

**Comment by David-Moreira** [comment]
Of course you also have the clear distinction of the namespacing, hell you can even go as far and do `Blazorise.TextEdit` if something similar to prefixing is important to you. 

You can always go to our docs and go through what we have available. Everything should be listed there with examples.
https://blazorise.com/docs

Some simpler input components are also predictable, we usually have Edit suffix for these. `TextEdit`, `NumericEdit`, `TimeEdit`, `DateEdit` but there can be advanced variations where we use Picker, `NumericPicker`, `TimePicker`, `DatePicker`, etc...
As any 3rd party library hopefully you'll get used to it as long as stuff is somewhat consistent and predictable.

Just let us know if you need anything else, going ahead and closing the issue (feel free to reopen if needed).

**Comment by Tony20221** [comment]
Other third party ui components uses prefixes to clearly distinguish themselves. 2-3 prefixes is not considered noise. That's pretty presumptuous to think... If a tag doesn't have a prefix it must be blazorise! Oh yeah... what if another ui component decides to do the same? It's a bit arrogant to think that all users will only use your component and nothing else.

Bad guideline.

**Comment by David-Moreira** [comment]
> Other third party ui components use prefixes to clearly distinguish themselves. They are all wrong abd you are right? 2-3 prefixes is not considered noise. That's pretty presumptuous to think... If a tag doesn't have a prefix it must be blazorise! Oh yeah... what if another ui component vendor decides to do the same? It's a bit arrogant to think that all users will only use your component and nothing else.
> 
> Bad guideline.

Hello @Tony20221 
Thank you for providing your input on this matter. Unfortunately this was a calculated design decision from the inception of the project by its creator @stsrki .

If you've been in Software Development for a while, you certainly know there's no sure fire way of developing a piece of software, and that's why there's a milion ways you can write Software, and so many frameworks, and just so many new things coming up every single year.... and it usually boils down to **pros & cons** of a certain architectural, design decision, framework....

We are not saying "they" are wrong and we are right. We are saying that we've made the decision to go with Prefixless components. It's not uncommon to have APIs with the same naming, and that's an issue that in computer science has already been well solved. Namespaces., that's a consensus we've gotten to, when defining boundaries in pieces of software, to use namespaces and everything gets resolved correctly.

Have you imagined if every dotnet api adopted the approach of using prefixes in their apis? That would seem hell of weird since you're not used to it. They just use clear well defined names within their namespaces. But, again, it could be otherwise, certainly that was also a design decision of theirs.

You can use as many component providers as you'd like, as long as you make use of namespaces, there should not be an issue with using `Blazorise` with any other component provider. Although it's very uncommon to use more then 1 component provider. (again going back to **pros & cons**, I'm sure you can find alot of cons to using more then 1 library provider in a single project, as I'm sure there could indeed be pros to using more then 1 according to your use case... fortunately we live in a world of choices. :)) 

As with anything, you're free to like our Software and our choices and use it, or even not like the choices we've made and still use if it's a good tool for your use case. But we can understand if, for you and your project this is a no go. You're free to choose.

But understand that we're indeed always open to hear suggestions or critiques but this is something that's a core part of our product, we do not have intentions of changing this. 

Thank you for your input on this matter.

**Comment by Tony20221** [comment]
Prefixes in apis? That makes no sense. The url is unique enough and it's related to the vendor.

Sure everyone is free to make a choice in what to use. After I learned I have to pay for a license for commercial uses, I decided to use a library that's free for commercial use.

**Comment by David-Moreira** [comment]
I think you have miss understand a Web Api endpoint url with just a regularly exposed api interface, as that's what I meant.... 

Api stands for advanced programming interface although a Web api is very genericly referred to as an Api that's not what I referred to. I referred to an api interface  in general...

Sure there are high quality free libraries but not everyone as the resources to put in the time to provide you with a free quality library so you yourself can make money. 

Again, thanks for your input. Best of luck on your endeavors.
