### ISSUE TITLE
[Bug]: ApplicationLoadingIndicator doesn't work for Blazor Server

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#4996]
### Blazorise Version

1.3.1

### What Blazorise provider are you running on?

Material

### Link to minimal reproduction, or a simple code snippet

If you start the blazor server sample app you dont see the loading indicator, but just a white page.

https://rcbootstrapdemo.blazorise.com/

### Steps to reproduce

Open https://rcbootstrapdemo.blazorise.com/

### What is expected?

Loading indicator is visible

### What is actually happening?

Nothing just a white page

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by njannink** [comment]
I dont know if this is acually inherent to Blazor server meaning that you will have to use a non-blazor solution to be able to show some kind of app loading status

**Comment by David-Moreira** [comment]
Heyia Is this actually related to an issue you're having on one of your applications?

As far as I remember we are not using the Blazorise Loading Indicator. It's just a div with an animation and the index.html loading before the wasm app is bootstrapped, as far as I remember.
For the server we probably haven't added any loading indication, again, as far as I remember.

So do you happen to have an issue with the component itself, or you just happened to notice that the Server version didn't have a loading screen?

**Comment by njannink** [comment]
I want to add an app loading indicator to our own application and indeed when I wanted to check the examples I noticed that it wasn't working / not added to the blazor server app example. So thats why I reported this. Might be that it indeed is just missing from the example. Later this week I will try to add it to our own app to see if it works

**Comment by David-Moreira** [comment]
Hello,
The example is here: 
https://rcbootstrapdemo.blazorise.com/tests/loadingindicator
https://bootstrapdemo.blazorise.com/tests/loadingindicator

And there should be documentation for it also. I think it's fine leaving the demo apps as they are otherwise. 
Since the examples are provided.

**Comment by njannink** [comment]
the loading indicator is indeed working, but not the indicator at application startup (this spinning blazorise image)

**Comment by David-Moreira** [comment]
> the loading indicator is indeed working, but not the indicator at application startup (this spinning blazorise image)

It seems like we didn't bother with it, since server loads right away.

**index.html** (wasm loading) (this contains) vs **_Host.cshtml** (server loading) (this does not contain)
Also the loading that's in there for wasm is straight up html/css since the app has not been bootstraped yet.
![image](https://github.com/Megabit/Blazorise/assets/22283161/acbe027d-efe2-429e-8300-e9410ec93b77)

So again, the startup is not using the **Blazorise Loading Indicator** at all.

**Comment by David-Moreira** [comment]
You can see **Blazorise Loading Indicator** working on a `Blazor.Server` application here:
https://blazorise.com/support/issues/1/welcome-to-the-official-blazorise-support-forum
Just refresh the page, and you should see a standard loading indicator come up for a brief seconds.

**Comment by stsrki** [comment]
The https://rcbootstrapdemo.blazorise.com/ is a Blazor Server hosted application, so there is no reason to add an indication since it loads immediately on the server and is server to the client. Only for WASM apps have we added spinning images since it takes a while until all the assemblies are downloaded.

**Comment by David-Moreira** [comment]
Going ahead and closing the issue. Please feel free to reopen if an actual issue is found with the Blazorize Loading Indicator.
