### ISSUE TITLE
DataGrid direct in grid editing (Excel like)

### ISSUE THREAD

**Issue by rbillott** [Megabit/Blazorise#5021]
**Is your feature request related to a problem? Please describe.**
Editing multiple records is not very user friendly.  

**Describe the solution you'd like**
You might be aware that one of your competitor 'mudblazor' has a **direct in-grid edit mode** which is **very nice**. The cell turns in edit mode as soon as it gets the focus and the value get auto committed when lose focus. (https://mudblazor.com/components/datagrid#editing) . Might not be for everybody but that's exactly what my users want.  They sometime need to edit quickly, bunch of records. And they are complaining a lot about the extra click needed to switch to edit mode and validate each time they need an edit.  

I can understand that there are some challenges and it can makes things pretty complicated but just wondering : **Are you considering implementing something like that ?**

**Comment by stsrki** [comment]
@David-Moreira, what do you think?

**Comment by David-Moreira** [comment]
Hello,

We already have an issue open to work on "bulk edit" which is scheduled for the next release: https://github.com/Megabit/Blazorise/issues/855

We haven't started work yet, but the excel like editing is what seems to make most sense when bulk editing, so that's what we'll be prioritizing. 
Basically our existing `DataGridEditMode.Inline` will be enchanced with bulk edit capabilities. That's what I'm thinking.

I don't know about our other two existing modes `DataGridEditMode.Form` and `DataGridEditMode.Popup`, as I'm not sure it makes much sense for these to be "bulk editable" and not a priority either, in my opinion.

I will be closing this issue as it is a duplicate. But please feel free to add any suggestions since we'll start working on the feature soon.
