### ISSUE TITLE
[Bug]: NumericEdit stripping trailing zeros when attempting to input a small decimal value

### ISSUE THREAD

**Issue by cory-west-neo** [Megabit/Blazorise#5076]
### Blazorise Version

1.2.4

### What Blazorise provider are you running on?

None

### Link to minimal reproduction, or a simple code snippet

Any usage of NumericEdit on a nullable decimal field will cause this issue

### Steps to reproduce

1. Have a model with a decimal? field.
2. Add a **<NumericEdit Value="Value"></NumericEdit>** component
3. Attempt to type any decimal value lower than 0.1

### What is expected?

Any value lower than 0.1 is correctly bound to the model

### What is actually happening?

When you input any 0 after the decimal point, it gets stripped, making it impossible to type 0.01 or 0.404 or 0.001.

### What browsers are you seeing the problem on?

Chrome

**Comment by stsrki** [comment]
Unfortunately, it seems there is no easy way around these limitations. It all comes down to how the browser works with native numeric inputs. See here for more info https://github.com/Megabit/Blazorise/issues/5090#issuecomment-1774615497

In this case, when we write "0.0" the browser figures that it is a full value and then triggers `onchange` event. Then we internally read that value and since we don't know the number of decimals we round it to `0`, Then we trigger `ValueChanged` which then triggers refresh and that refresh tells Blazor to redraw NumericEdit. Redraw updates the Value, and updates the caret position.

My advice is as always use the NumericPicker component which was created just because of these limitations.

Ps. I will now close this ticket.

**Comment by cory-west-neo** [comment]
Thanks for the update. Is there something we could put in the documentation to bring light to this issue? Or did I miss something already there that would have pointed me to this conclusion. The workaround is satisfactory, I just didn't know about it.

**Comment by stsrki** [comment]
There is this

![image](https://github.com/Megabit/Blazorise/assets/900302/781e54e1-06f6-459c-90db-ec2847c0f95d)

But, I think we need to expand on it and make it more clear about the possible limitations.
