### ISSUE TITLE
Tooltips do not display correctly on pages when Blazor 8 Enhanced navigation loads the page

### ISSUE THREAD

**Issue by oliverw** [Megabit/Blazorise#5127]
### Blazorise Version

1.3.2

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

When using the Blazorise Tooltip component on a page loaded using  Blazor 8 Enhanced navigation, the tooltip lacks border, padding and the arrow symbol. Technically they work but look rather rough.

![image](https://github.com/Megabit/Blazorise/assets/51688/c7a808f6-6bb8-4c01-8937-68646ba0840c)

### Steps to reproduce

Load a page containing Blazorise tooltips using enhanced navigation in Blazor 8.

### What is expected?

Tooltip displays correctly styled.

### What is actually happening?

Tooltip lacks styles.

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by stsrki** [comment]
Is there any chance you could create a small project to reproduce the problem on our side?

**Comment by oliverw** [comment]
Are you not testing the library with .NET 8 Blazor?

**Comment by stsrki** [comment]
Yes, we are testing in .NET 8 so that we are ready once the final version comes out.

Here is our tooltip in action and as you can see it works.

![image](https://github.com/Megabit/Blazorise/assets/900302/8649d125-765a-454d-87f3-ccb5b8aa60de)

---

It's hard to test in all situations. That's why we prefer to have a reproducible as that way we can fix any issue much faster.
