### ISSUE TITLE
[Bug]: Validation Autocomplete with multiple not showing red outline

### ISSUE THREAD

**Issue by benny-adiwijaya** [Megabit/Blazorise#5158]
### Blazorise Version

1.2.5

### What Blazorise provider are you running on?

Bootstrap4

### Link to minimal reproduction, or a simple code snippet

https://bootstrapdemo.blazorise.com/tests/autocomplete

### Steps to reproduce

add Validator="@ValidationRule.IsNotEmpty" on Autocomplete

### What is expected?

Show red outline when empty

### What is actually happening?

red outline not show
<img width="937" alt="Screenshot 2023-11-23 at 14 50 33" src="https://github.com/Megabit/Blazorise/assets/59247546/59d1eeff-23d8-4284-beb2-6d5bccba3830">

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

Is there a way to show red outline when empty? Thanks

**Comment by David-Moreira** [comment]
Hello @benny-adiwijaya 
It seems like our styling for multiple selection is conflicting with the styling for the validation.
A class is added whenever it's in an invalid state.
You should be able to use the **is-invalid** class to add something like `border: 1px solid #dc3545;` in order to re-override and get the border.

**Comment by David-Moreira** [comment]
On a side note, from some testing it seems like maybe the `Validator` is not working too great with multiple selection. so we need to take a look at that. 
Since apparently even if there's a selection, it shows as invalid.

**Comment by David-Moreira** [comment]
Closed by https://github.com/Megabit/Blazorise/pull/5256
