### ISSUE TITLE
[Bug]: Bazor server .NET8 - Layout Sider not show side menu

### ISSUE THREAD

**Issue by Valerio81** [Megabit/Blazorise#5166]
### Blazorise Version

1.3.3

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

[code.zip](https://github.com/Megabit/Blazorise/files/13485896/code.zip)

### Steps to reproduce

- All external files are copied in local (css or js) folder
- Added all Blazorise packages from NuGet (Blazorise, Blazorise.Bootstrap5, Blazorise.Components, Blazorise.Icons.FontAwesome, Blazorise.LoadingIndicator
- Copy/paste razor code from Blazorise WASM template to new Blazor NET8 server app
- Added "@using Blazorise;" and "@using Blazorise.LoadingIndicator" to _Import.razor file

### What is expected?

I expect same layout as Blazorise WASM template

### What is actually happening?

MainLayout -> OK
TopMenu -> OK
SideMenu -> KO -> not showed (but the code is rendered in HTML)

**Comment by David-Moreira** [comment]
If I have to guess you're using Server Side Rendering (SSR) and not actual Blazor.Server(SignalR) model. 
Blazorise components were all designed in the original models, for interactivity and should be used in Blazor.Server and Blazor.WebAssembly models currently.

**Comment by Valerio81** [comment]
Hi David,
I think i'm using the interactive mode. In my Program.cs there is this line

builder.Services.AddRazorComponents().AddInteractiveServerComponents();

This is the configuration i chosen on VS:
![image](https://github.com/Megabit/Blazorise/assets/16916271/28de96aa-7e1a-4f0d-b01e-1942cbfcdf16)

**Comment by David-Moreira** [comment]
The interactivity location is set per page/component. Typically the Blazorise Layout is found on a Layout page. If this is the interactivity you have chosen it will not set the Layout page as interactable. 

I suggest making it global and get acquainted with the differences and how to control Static Server Rendering (if you really need it) vs Interactive Rendering.

But I have to say, it would probably be great if there was an optimized version of the Layout component for Static Server Rendering that would still keep most of the static functionality intact (navigate, responsive, etc...). 
We'll have to do some investigation on that matter. 
@stsrki does it look viable? 

But again, for now, make sure the Blazorise components are rendered as interactive for proper interactive support.

**Comment by stsrki** [comment]
> But I have to say, it would probably be great if there was an optimized version of the Layout component for Static Server Rendering that would still keep most of the static functionality intact (navigate, responsive, etc...).
> We'll have to do some investigation on that matter.
> @stsrki does it look viable?

I don't think it's a good idea. Blazor team advises library vendors to not make components targeting specific rendering modes but to make them in a way that the component is not obvious to any rendering in particular.

**Comment by David-Moreira** [comment]
> > But I have to say, it would probably be great if there was an optimized version of the Layout component for Static Server Rendering that would still keep most of the static functionality intact (navigate, responsive, etc...).
> > We'll have to do some investigation on that matter.
> > @stsrki does it look viable?
> 
> I don't think it's a good idea. Blazor team advises library vendors to not make components targeting specific rendering modes but to make them in a way that the component is not obvious to any rendering in particular.

Right I'm not saying to target a rendering system. I'm saying if we can optimize it, so when it gets static rendered the user still gets the static html which might be enough for navigation & responsiveness, because currently, it's most likely not getting rendered due to some visible flag being set to false when it initializes.

**Comment by David-Moreira** [comment]
> > > But I have to say, it would probably be great if there was an optimized version of the Layout component for Static Server Rendering that would still keep most of the static functionality intact (navigate, responsive, etc...).
> > > We'll have to do some investigation on that matter.
> > > @stsrki does it look viable?
> > 
> > 
> > I don't think it's a good idea. Blazor team advises library vendors to not make components targeting specific rendering modes but to make them in a way that the component is not obvious to any rendering in particular.
> 
> Right I'm not saying to target a rendering system. I'm saying if we can optimize it, so when it gets static rendered the user still gets the static html which might be enough for navigation & responsiveness, because currently, it's most likely not getting rendered due to some visible flag being set to false when it initializes.



> > > But I have to say, it would probably be great if there was an optimized version of the Layout component for Static Server Rendering that would still keep most of the static functionality intact (navigate, responsive, etc...).
> > > We'll have to do some investigation on that matter.
> > > @stsrki does it look viable?
> > 
> > 
> > I don't think it's a good idea. Blazor team advises library vendors to not make components targeting specific rendering modes but to make them in a way that the component is not obvious to any rendering in particular.
> 
> Right I'm not saying to target a rendering system. I'm saying if we can optimize it, so when it gets static rendered the user still gets the static html which might be enough for navigation & responsiveness, because currently, it's most likely not getting rendered due to some visible flag being set to false **or some missing class** when it initializes.
> 
> Another idea is to make a new static based component people can use (it can be a separate lbirary to make it easier to discern). I am advocating for this specially on the **Layout** component, for a good reason. If you can Static Server Render a layout page, it will be much faster then the setup of blazor components. (for people who need this snappyness).
> 
> (I.e someone has a home page mainly staticly rendered (with blazorise layout), and then can use the interactive blazor components separately, currently user has to make everything interactive, because of the layout)

**Comment by stsrki** [comment]
PS.

![image](https://github.com/Megabit/Blazorise/assets/900302/4dd9e20d-ea71-42bb-bcc0-b3cd0cc7f2b3)

**Comment by David-Moreira** [comment]
> But wouldn't making the Layout component interactive also make everything inside of it interactive? Since everything in the user app is contained inside of a Layout component?

What do you mean?
Also you can't specifically make layouts interactable as far as I know, you have to make the app globally interactable, by making the Router interactable, we had this issue when updating our docs. 

--- 

Forget any of the Microsoft notes, please... Although they do say "should degrade gracefully when rendered statically" which is what I am advocating for...

I'm gonna give you an example:

I have an application where I want to add Blazorise interactivity to some pages, but not all. I want to have the best of both worlds with the new **.NET8 feature Static Server Render!**

So:
- My homepage will just be statically rendered, so it will be super fast, way faster then currently we can do with Blazor models.
  - This is great for people who have public facing sites and really need the first page load to be real fast
- My Counter Page will have an interactive counter component that I want to be interactive, this is using blazorise components, everything should work fine, I'll make the whole page **rendermode=InteractiveAuto**

I have a **MainLayout**
- If I don't use Blazorise Layout, and I just grab the bootstrap css for how the layout works, everything will work great as I want it to, this layout will get statically rendered in both home and counter pages. (I don't know if currently bootstrap requires js to make the layout fully work, if it doesn't, it further cements my opinion that it could just work statically)

- If I use Blazorise Layout currently, I expect to loose interactivity, yes (hamburguer menus, etc...)
  But I expect the static html that gets rendered still is enough for layout + navigation. It might not even be working fully interactive wise, but I still would expect that the visual UI element would show. Currently the html does not even show, in my opinion, it probably should even **if NOT INTERACTIVE**
I am almost certain I could go grab bootstrap css make a new Layout component which would work fine with static server side rendering. and then I could add interactivity to it, like hamburguer menus, but those would only work in an interactive mode as expected (if using c# instead of js).


This might not be easy to explain... And it might not even be viable, I was just throwing it out there, but the reasons you are giving me for not being viable are not what I would expect. 

**I'd expect some reason like :** Layout can never be rendered statically because the side menu structure must be hidden initially for some reason...

Let me know if you want to setup a meeting...or just disregard this alltogether.

**Comment by David-Moreira** [comment]
I'm so glad they put this into the notes.. `"should degrade gracefully when rendered statically"` this is more or less what I'm talking about.
https://developer.mozilla.org/en-US/docs/Glossary/Graceful_degradation

**Comment by Valerio81** [comment]
Ok, thanks.
Problem solved 

> The interactivity location is set per page/component on the screenshot you have posted. Typically the Blazorise Layout is found on a Layout page. If this is the interactivity you have chosen it will not set the Layout page as interactable and it will be static rendered instead.
> 
> I suggest making it global and get acquainted with the differences and how to control Static Server Rendering (if you really need it) vs Interactive Rendering.
> 
> But I have to say, it would probably be great if there was an optimized version of the Layout component for Static Server Rendering that would still keep most of the static functionality intact (navigate, responsive, etc...). We'll have to do some investigation on that matter. @stsrki does it look viable?
> 
> But again, for now, make sure the Blazorise components are rendered as interactive for proper interactive support.

Thanks for the suggestion.
Problem solved adding global interactivity to my project.
