### ISSUE TITLE
[Bug]: Column Chooser should show without requiring the pager to be visible.

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#5381]
### Blazorise Version

1.5.0

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

https://blazorise.com/docs/extensions/datagrid/features/column-chooser

### Steps to reproduce

https://blazorise.com/docs/extensions/datagrid/features/column-chooser

### What is expected?

Column Chooser should be visible if ShowColumnChooser = true

### What is actually happening?

Column Chooser is only visible when  ShowColumnChooser = true and  ShowPager=true

### What browsers do you see the problem on?

Microsoft Edge

### Any additional comments?

Documentation isn't consistent with property names
![image](https://github.com/Megabit/Blazorise/assets/34929316/ba8f2fe6-3749-4ccb-8d5f-1a0c6ba68904)

**Comment by mtbayley** [comment]
Is it possible to have the column chooser work outside of a pager?
Or maybe some kind of Data Grid toolbar that is customizable?
Pager isn't a great name for it anymore if there is going to be other stuff shown.
This may help solve my feature request https://github.com/Megabit/Blazorise/issues/5382

**Comment by David-Moreira** [comment]
I guess you're right. We are kinda using the pager as an all purpose toolbar. So the naming is unfortunate.
I'm not sure about changing the name at this time though it's already been like that since forever, people might be used to it.
I would agree with the pager showing just the column chooser if `ShowColumnChooser` is set to true. And not needing to set `ShowPager` explicitly to true.
@stsrki thoughts?

**Comment by stsrki** [comment]
> I would agree with the pager showing just the column chooser if `ShowColumnChooser` is set to true. And not needing to set `ShowPager` explicitly to true.

I agree.

Regarding the naming of the pager. We definitely need to find a better name.
