### ISSUE TITLE
[Bug]: SelectList binded selected values not working properly when they contain commas

### ISSUE THREAD

**Issue by alex-hall-idener** [Megabit/Blazorise#5388]
### Blazorise Version

1.5.0

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

```
<SelectList TItem="string"
            TValue="string"
            Data="@(new List<string>{"1,9", "4", "78,4"})"
            Multiple
            TextField='@((item)=>item)'
            ValueField="@((item)=>item)"
            @bind-SelectedValues="@aux"
            Class="form-select" />
			
@code
{
    IReadOnlyList<string> aux = new List<string>();
}
```

### Steps to reproduce

1. Select one of the elements that contains a comma (for example, "1,9"). It won't get selected.
2. Select it again for it to be selected.
3. Check the contents of the binded list.

### What is expected?

- The item in the select list should get selected with only one click.
- The binded list should only have one item inside.

### What is actually happening?

- Items that contain commas aren't selected when clicking on them once.
- The binded list contains the item that contains a comma split into two items.

### What browsers do you see the problem on?

Chrome

**Comment by David-Moreira** [comment]
@stsrki 
The problem is with how we handle multiple values internally in select.
We receive an array of strings and internally convert it to a string delimited by commas.
![image](https://github.com/Megabit/Blazorise/assets/22283161/667dfe72-82c5-4a28-8486-5deacde4ce36)

This will naturally not handle any bound values with commas correctly.

---
@stsrki 
Before I go making any changes whatosever, we need to understand what is the best course of action.
First, this seems to arise by how we handle everything internally, where we always try to make it so everything goes through a pipeline of 

- blazor sends the value on the event handler arguments
- We transform into something the `CurrentValueHandler(string value)`  can digest
- into `ParseValueFromStringAsync(string value)` 

this means, there will be cases like this, that if we need to do tricks to transform the actual value into something that `CurrentValueHandler` and `ParseValueFromStringAsync` can work with. 

**Solution 1.** I understand that for most of inputs, this just works, but should this system be more flexible somehow in order to allow other type of values, instead of doing these transformations? In this case we already had the array to work with, it's a shame we have to convert it to string and then convert back? (I'm not sure if we also have that "issue" other places?)

**Solution 2.** Treat it as an off case, and make the `MULTIPLE_DELIMITER` configurable by the consumer.

**Solution 3.** `MULTIPLE_DELIMITER` make the delimiter a character that's even more unlikely to show, although the problem will always exist for that specific character! Or use a special string as the delimiter i.e: **"__SELECT__DELIMITER__"**, which should make it super unlikely this would ever be a problem. (Altought obv a little less performant)

... Any other solution you might think off?

**Comment by David-Moreira** [comment]
@alex-hall-idener As for a temporary workaround I have to ask you to refrain from using the comma for now for the value.
You could use something like `{"1.9", "4", "78.4"}` for your values, and then replace them back with commas once you make use of the selected values.

**Comment by stsrki** [comment]
From what I remember, I used MULTIPLE_DELIMITER as a way to make it go through the same pipeline as all other input components. This was needed because we don't want to have edge cases where some components would have different validation and other rules. As always, there are tradeoffs.

I think the best way forward is to use some other delimited instead of `,`. Maybe even some combinations of characters that is unlikely to be used by the users.

Later we can also introduce a parameter to define the delimiter by the developer.

**Comment by David-Moreira** [comment]
Ok, so solution 3. Please let me know a delimiter.

**Comment by stsrki** [comment]
> Yes you reiterated what I said, you do it for the sake of going through the same pipeline, but could the pipeline be improved such that it handled generically or something?

Hardly. In the end, everything ends in the DOM as a string representation of the provided value. So we don't have much room for improvements over it.

**Comment by stsrki** [comment]
Regarding the delimiter, I propose

- `|~|`
- `~~`

**Comment by David-Moreira** [comment]
First one then. Second one... you never know...

**Comment by David-Moreira** [comment]
> > Yes you reiterated what I said, you do it for the sake of going through the same pipeline, but could the pipeline be improved such that it handled generically or something?
> 
> Hardly. In the end, everything ends in the DOM as a string representation of the provided value. So we don't have much room for improvements over it.

Right, if this is an off case, and other components don't really send you the value in it's proper "type form".. bool, numeric, etc... it's just a string for the most part, then I agree there would be little benefit.
