### ISSUE TITLE
[Bug]: VTable setup of type Blazorise.Bootstrap.BootstrapClassProvider failed

### ISSUE THREAD

**Issue by perphucthinh21** [Megabit/Blazorise#5440]
### Blazorise Version

1.4.1

### What Blazorise provider are you running on?

Bootstrap4

### Link to minimal reproduction or a simple code snippet

http://123.25.26.13:5000/

### Steps to reproduce

- Install Blazorise.Boottrap
- Then  context.Services
     .AddBlazorise(options =>
     {
         options.Immediate = true;
     })
     .AddBootstrapProviders()
     .AddFontAwesomeIcons();

### What is expected?

Running on the deployment environment

### What is actually happening?

I can run the code in localhost, but when I deploy it to IIS the UI doesn't start. I try to show the log and see the error is: VTable setup of type Blazorise.Bootstrap.BootstrapClassProvider failed

![image](https://github.com/Megabit/Blazorise/assets/42728774/ca5c556c-aa10-43c1-ad15-e6251af3f17b)

### What browsers do you see the problem on?

Chrome

### Any additional comments?

![image](https://github.com/Megabit/Blazorise/assets/42728774/ca5c556c-aa10-43c1-ad15-e6251af3f17b)

**Comment by stsrki** [comment]
From what I can see and by quick googling, the problem is not in Blazorise. 

- https://github.com/dotnet/maui/issues/3501
- https://stackoverflow.com/questions/62447717/system-typeloadexception-vtable-setup-of-type-xamarin-forms-formsandroidplatf
- https://github.com/dotnet/runtime/issues/30369

Can you confirm in your project that you use the same Blazorise assembly version across all projects? Also, make sure that you use the same version for other third-party assemblies.

**Comment by perphucthinh21** [comment]
Thank you for your fast reply. 
I use Abp Framework and they are using Blazorise in these packages. I don't know how to check the version of Blazorise that they used.
I'll do some research with the ABP instead

![image](https://github.com/Megabit/Blazorise/assets/42728774/9c74ea58-7294-47e8-b5f6-eb77fa6c55c7)
![image](https://github.com/Megabit/Blazorise/assets/42728774/92c08edc-b11c-452a-afd4-52d4db2cd65a)

**Comment by perphucthinh21** [comment]
Thanks @stsrki . It's working now. So I have to upgrade all related ABP packages to version 8.0.5 then the issue is gone.
