### ISSUE TITLE
[Bug]: Renewed license token not woring

### ISSUE THREAD

**Issue by tacoWanneeJama** [Megabit/Blazorise#5524]
### Blazorise Version

Latest

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

After renewing the Blazorise license I put in the new product token in my application. Now it complains about a not-licensed application. I use the token starting with: "Cjx...".
What do I do wrong?
![image](https://github.com/Megabit/Blazorise/assets/76042577/c24bc479-b65d-451f-818b-b7e18b8ad236)

### Steps to reproduce

See above

### What is expected?

No license warning

### What is actually happening?

License warning in console

### What browsers do you see the problem on?

Chrome

**Comment by tacoWanneeJama** [comment]
After a license renewal I have to manually revoke the old taken and generate a new one?
Why is not automatically a new token generated when the license renewal is accepted?

**Comment by stsrki** [comment]
Yes, the product token must be manually revoked and then generated with the new license. We could automatically do that for you; I admit it is not a bad idea. But, since the token is still validated offline, you would still have to manually copy/paste it to your app.

@David-Moreira, do you think we could at least regenerate the token automatically?

**Comment by David-Moreira** [comment]
If you want to keep using the latest Blazorise version indeed, you need to regenerate the product token.
But the old product token is still valid for older versions for the license period that you have bought.
So if we were to regenerate, this old product token would be lost.

But since the latest product token will always be the most permissive version wise, maybe it's indeed worth it. I'm just not sure if that's even more confusing to the user or not? He gets to the dashboard and the product token does not match what he has currently?

And If I remember correctly we implemented a warning in the dashboard that let's the user know the product token is stale, did that warning not show to you @tacoWanneeJama ?

**Comment by tacoWanneeJama** [comment]
David, I did not see any warnings in the portal about the license being stale or any mail about it.

**Comment by David-Moreira** [comment]
@stsrki want to go with auto regenerate? Or making sure that the warning is there instead? (Something like a yellow exclamation mark)

**Comment by stsrki** [comment]
No, I would rather it stays as it is. For example, every third-party service that I use that can have some kind of API key or similar after an expiration will not regenerate. I must personally log in and generate a new key and/or invalidate the existing one before regenerating.

So, instead of generating a new key automatically, I would notify by email and explain that the new token must be regenerated. Also, explain in the documentation the steps required.

**Comment by David-Moreira** [comment]
Ok that seems ok to me, improve on notification instead.

**Comment by David-Moreira** [comment]
This has now been improved. 
- An alert should show up by the Product Token if it finds the Product Token might be invalid for newer releases
- In the email there should be improved instructions about the Product Token usage and the need to renew it, something along these lines :

> "Once your account is activated, you will be able to generate a Product Token that you can use to activate your Blazorise components
Please take note that this Product Token will only be valid for the duration of your license.
You can generate a new Product Token at any time and are required to do so once your license is renewed."

Closing issue.
