### ISSUE TITLE
[Bug]:  SignaturePad -- update SignaturePad.razor.cs to include latest vendor options: options.ratio

### ISSUE THREAD

**Issue by sks-ttaylor** [Megabit/Blazorise#5629]
### Blazorise Version

1.5.3

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

https://bootstrap5demo.blazorise.com/tests/signaturepad

### Steps to reproduce

Using Chrome latest.

browse to https://bootstrap5demo.blazorise.com/tests/signaturepad

add signature to canvas,  the preview is 2.5 (window.devicePixelRatio) the size.

With updating SignaturePad.razor.cs to include a [Paramter] public Ratio, it can be passed to the vendor code.  

### What is expected?

i expect 1-to-1 Ratio 

### What is actually happening?

In Chrome, the ratio is window.devicePixelRatio (2.5) so the size of the image is that much bigger.

### What browsers do you see the problem on?

Chrome

**Comment by stsrki** [comment]
Hello @sks-ttaylor 

I have committed to this issue, and as I see it, it works as expected. However, it might not look at first. When we have a higher DPI we need to take into account that signature pad needs to remain at the same size visually on mobile and on desktop. So, we calculate the canvas size of the signature pad based on the DPI. 

When the canvas content of that recalculated size is converted back to the image data, it needs to convert it to a "real world" size that will keep all the details that are present in the higher DPI. That's why the end result image is larger. We cannot resize an image. Otherwise, we would lose any fine details that were present in the higher DPI canvas.

If you want to the preview at the same size you only need to define the image size at `100%`. See an example:

![image](https://github.com/user-attachments/assets/69c8c530-10ac-40d3-a7cb-50244692b1b1)

**Comment by stsrki** [comment]
PS. This should work as expected

`<Image Source="@Image64" Fluid />`
