### ISSUE TITLE
Tooltip delay

### ISSUE THREAD

**Issue by stsrki** [Megabit/Blazorise#5686]
Add an option to delay the showing and hiding of tooltips.

https://atomiks.github.io/tippyjs/v6/customization/

**Comment by blenke** [comment]
Thank you for adding this. Very useful.
Would it be possible to add default delay values and fade values to the Blazorise options in program.cs so that we don't have to add this to each individual tooltip. Seems more logical to me, especially when you have forms with lots of inputs. I don't think you will often have a different delay value within the same form (or even application)

**Comment by stsrki** [comment]
> Thank you for adding this. Very useful. Would it be possible to add default delay values and fade values to the Blazorise options in program.cs so that we don't have to add this to each individual tooltip. Seems more logical to me, especially when you have forms with lots of inputs. I don't think you will often have a different delay value within the same form (or even application)

I must admit it didn't come to mind, but adding new options shouldn't be much of a problem. Going on the list as it is now a perfect time to implement it.

**Comment by blenke** [comment]
Great, perhaps you should set a default value that is similar to a standard tooltip. I could find what that should be though, apparently browser dependent, but i would guess something like 500ms.
