### ISSUE TITLE
Add Mixed Styles With RadioGroup Buttons

### ISSUE THREAD

**Issue by mtbayley** [Megabit/Blazorise#5728]
Currently, all colors are the same with the Color parameter on RadioGroup. I'm requesting an easy way to customize the colors per button. See bootstrap docs.

https://getbootstrap.com/docs/5.3/components/button-group/#mixed-styles

![image](https://github.com/user-attachments/assets/8681d2bb-635a-412c-9d8e-048d958d91c4)

**Comment by stsrki** [comment]
The example you posted is for the button group. We already support setting each individual button color for button groups. See the docs https://blazorise.com/docs/components/button

For RadioGroup, it is a different story because they are a "hacked" version of buttons that are applied to the `label` TAG. While it would work initially, it would not be ideal. For example, border colors would be different for _buttons_. 

We don't have plans to add this feature at the moment.

**Comment by mtbayley** [comment]
I don't understand what you mean by the border colors. I was able to modify the colors in the DOM to make the demo show what I want.
![image](https://github.com/user-attachments/assets/26e3bced-5959-47e2-a74d-ae78db99f414)

But I'll see what I can cobble together with the button group instead

**Comment by stsrki** [comment]
By border colors, I meant all of the styles. For hover, active, disabled states. They could leak into neighboring buttons and could look weird. But, I could be wrong. So, I need to try it and see how it goes.
