### ISSUE TITLE
Undeprecate CellStyle / CellClass

### ISSUE THREAD

**Issue by lprichar** [Megabit/Blazorise#5773]
Deprecating CellStyle and CellClass at the DataGridColumn level in favor of CellStyling at the DataGrid level seems pretty inconvenient for simple cases like just disabling line wrapping for a particular column.  The CellStyling lambda provides a DataGrid column which I guess theoretically could be used to find the column that I want to apply the style/class to, but how?  Some columns have a Field property that I guess you could use, but it's not required, and my command columns will definitely not have it.  If there were an ordinal property it would help, but we don't currently get that.  Worse if I have 2 or more columns that I want to apply a CellStyle or a CellClass to now I have to write a switch statement or something which will be really ugly.  I can imagine CellStyling could be very useful and powerful in certain circumstances, but please consider making it's use optional for simpler cases by undeprecating CellStyle and CellClass.

**Comment by stsrki** [comment]
We have introduced new APIs https://github.com/Megabit/Blazorise/pull/5122/files#diff-156a5bc6c34c42dbc664816b53d988f4b1dc5dd9d082f44ae3885b00513b8d70R132, so that we could simplify the usage of DataGrid in the long run. We didn't want to have too many different APIs for the same thing, so we went with the `Styling` APIs as they are more feature rich. So we don't have plans to keep obsolete APIs.

I can understand that it is difficult to customize them when columns are not bound to any field. For those, you still have a way of figuring it out. The second argument of lambda should be the column reference. 

@David-Moreira Do you agree?

**Comment by David-Moreira** [comment]
The concern is valid indeed. Feels like at least you should be able to quickly apply a **class** or **style** if you wanted to, as that mimics how you would style an html element.
Maybe we should take the hit of having more then one way to do it for flexibility.

If we don't concede on this aspect, I believe that at least the column has an **ElementId** that can be assigned? It should be able to be identified in this way.
Nevertheless, it seems to break a bit of the rapid development spirit, where just to define a class or style for a particular column, you need to add a method and if statements.

**Comment by blenke** [comment]
I would like to support this request. I used it to highlight specific values in tables, like this: 
```CellStyle="@((item) => (item.Value>100) ? "background-color:lightyellow" : "")"```

The CellStyling I need to add the column name and it would look like this:
```
CellStyling="@((item, Column, styling)=>
{ styling.Style= (item.Value>100 && Column.Field==nameof(MyObject.Value)?"background-color:lightyellow":"";  })"
```
In case you have multiple columns where you would want to change the cellstyle the code would become more extensive. Having the cellstyle on the column avoid this.

**Comment by stsrki** [comment]
I guess we have no other choice than to revert the changes.
