### ISSUE TITLE
Video: Disable Fullscreen

### ISSUE THREAD

**Issue by thumaman** [Megabit/Blazorise#5775]
Hi, 

is there any way to disable the video to enter fullscreen if a user double taps on a video.

**Comment by stsrki** [comment]
When you assume that it will be easy...

It turns out it is not possible. 

![Image](https://github.com/user-attachments/assets/71ebf305-59c5-48a5-9949-885244bdc4c9)

and

![Image](https://github.com/user-attachments/assets/b12f95ec-6196-44f5-8b52-cf28528cf333)

---

Even if we define `canFullscreen` it is not guaranteed to work. I'm testing it locally, and for me, it doesn't work. Now, I could push these changes, and you could use them, but be aware that it will have some limitations.

I will try to open a ticket on Vidstack and see what they have to say about it.

**Comment by stsrki** [comment]
https://github.com/vidstack/player/discussions/1470

**Comment by stsrki** [comment]
I was able to find the right option. 

https://github.com/Megabit/Blazorise/pull/5776

**Comment by thumaman** [comment]
Great,

thank you for your help.

When will these changes be available? In 1.7. release?

**Comment by stsrki** [comment]
The plan was for Oct 15th, but since we still have some outstanding tickets, we will postpone it by a few more days.

**Comment by thumaman** [comment]
Is this functionality available in 1.6.2?

**Comment by stsrki** [comment]
No, in 1.7 only. You can see the milestones on the sidebar of each task. That way, you can know which release it will be released next.

**Comment by thumaman** [comment]
Would it be possible to release it sooner since it is a very minor change?

**Comment by stsrki** [comment]
Yes, I have released a 1.7 preview now. Please try it.
